box.json
@danepowell I have no idea if this is the right way to do this.
=> Fixes #121: Ship required .sh file with phar.

box.json
=> Reduce phar size with compactors

RELEASE.md
It's fairly straightforward right now but always good to document for posterity.
=> Document release process.

src/Command/CommandBase.php, src/Command/RefreshCommand.php, src/Helpers/LocalMachineHelper.php, tests/phpunit/src/Commands/RefreshCommandTest.php
=> Do not clone into dir with existing .git repo.

bin/acli
=> Cannot run on Windows Powershell.

README.md
I think this might keep it up to date, see https://github.com/lemurheavy/coveralls-public/issues/971#issuecomment-338942441
=> Refresh coveralls token

src/Command/NewCommand.php, tests/phpunit/src/Commands/NewCommandTest.php
@anavarre @grasmash This means that we will be creating Drupal 9 projects by default (instead of Drupal 8). I think that's desirable, but it's a big change.
=> Use Acquia project templates for acli new

composer.lock, src/Command/Ide/IdeListCommand.php, symfony.lock, tests/phpunit/src/Commands/Ide/IdeListCommandTest.php
Depends on https://github.com/typhonius/acquia-php-sdk-v2/pull/78
=> Fixes DT-1922: Add owner information to ide:list

README.md
=> Clarify the php-phar extension needs to be installed

src/Command/RefreshCommand.php
=> Revert "Fixes #246: PHP notice with acli refresh when selecting a DB."

README.md
These already exist on docs.acquia.com, I'd rather not have them duplicated and have to keep them always up to date.
=> DX-2508: Clean up docs

bin/acli, src/Command/ClearCacheCommand.php, src/Command/CommandBase.php, src/Command/Remote/DrushCommand.php, src/Command/Remote/SshCommand.php, tests/phpunit/src/Commands/ClearCacheCommandTest.php, tests/phpunit/src/TestBase.php
=> Cache command aliases.

composer.json, composer.lock
I think this upstream PR will be merged soon, but until it is, @anavarre and I think it's best to fork that repo so we can get a new release out with a full backwards-compatible self-update command.
https://github.com/consolidation/self-update/pull/5
=> Fork consolidation/self-update until PR is merged

tests/phpunit/src/Commands/Ide/Wizard/IdeWizardCreateSshKeyCommandTest.php
Motivation
----------
Fixes #352
Replaces #377 
---------
Mock the method that adds keys to the SSH agent. This avoids actually invoking an SSH agent (on the host machine) when running tests.
Testing steps
---------
Really the only important thing is that tests pass and coverage stays the same. But if you want to replicate the original issue, disable your local SSH agent or use an environment like WSL where it's not supported.
3. Run `composer test`
4. Verify there are no failing tests due to missing SSH agent.
=> DX-2786: Mock SSH agent methods

.travis.yml, composer.json, composer.lock, config/services.yml
Motivation
----------
Fixes #367
---------
- Add PHP 8 to composer.json
- Add PHP 8 to Travis tests
=> Fix #367: Support PHP 8.0

assets/acquia-spec.yaml, src/Command/Api/ApiCommandHelper.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php, tests/phpunit/src/Commands/Remote/DrushCommandTest.php, tests/phpunit/src/Commands/Remote/SshCommandTest.php
Looks like, among other things, these commands were added:
* applications:search:configuration-set-list
* applications:search:configuration-set-create
* applications:search:configuration-set-find
* applications:search:configuration-set-delete
* applications:settings-list
* applications:hosting-settings-list
* environments:clear-caches
* environments:cdn-find
* environments:cdn-enable
* environments:cdn-disable
* environments:domain-uptime-scan-find
* applications:settings-list
* applications:hosting-settings-list
=> Updating Acquia Cloud specification.

composer.json, composer.lock, symfony.lock
**Motivation**
Fixes #467
Patch Acquia CLI to include https://github.com/symfony/symfony/pull/40450, until that's merged and we can update to a new Symfony release that includes the fix.
Wait until the Symfony release and just suffer the bug.
=> Fix #467: Spinners clear terminal output

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullCodeCommandTest.php
=> Fixes #491: In Cloud IDE, do not ask whether to clone a project in the project directory.

src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php
=> Fixes #492: Indicate backup age.

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/CommandTestBase.php
**Motivation**
Fixes #493
Instead of reading the contents of the backup file into memory before dumping to disk, just write it to disk as a stream.
None, this is absolutely the right way to do it 😄 
@anavarre can you please help test? I don't have access to any database large enough to reproduce the issue or confirm that it fixes it.
=> DX-3643: [pull:db] improve memory usage

src/Command/CommandBase.php, src/Command/Pull/PullCommandBase.php, src/Command/Push/PushDatabaseCommand.php, src/Command/Push/PushFilesCommand.php, tests/phpunit/src/Commands/Push/PushDatabaseCommandTest.php
Fix #522
Correctly identify the tmp directory on ODEs.
=> Fixes #522: ACLI fails to push the database.

composer.json
**Motivation**
Fixes #505
Indent composer.json at 4 spaces to conform to the de facto standard
=> Fix #505: Indent composer.json 4 spaces

src/Command/Ide/IdeCreateCommand.php
=> Fixes #528: Accept IDE label via --label option.

composer.json, composer.lock
**Motivation**
Symfony cut a new release that includes this patch, so there's no reason to continue maintaining it.
Remove patch and update Symfony.
3. Test for regressions (should be no functional changes)
=> DX-3701: Unpatch Symfony console

README.md, composer.json, composer.lock
=> Adding violinist.

src/Command/Ide/IdeCreateCommand.php
**Motivation**
Add validation to the label input when creating an IDE.
3. Run `acli ide:create --label='1234!@#$'` and observe it fails
4. Run `acli ide:create` and manually input `!@#$`, observe it fails
5. Run `acli ide:create --label="Test This"` and observe it passes
=> Add validation for IDE labels

assets/acquia-spec.yaml, tests/phpunit/src/TestBase.php
CXAPI was updated to include these keys, so we no longer need to add them.
=> Remove Cloud API balancer/platform workarounds

MAINTAINING.md
Documenting how to create a new release.
=> Add release instructions to MAINTAINING.md.

src/Command/DocsCommand.php
**Motivation**
Make viewing Acquia CLI docs easier.
Adds `acli docs` command.
None.
3. Run `acli docs`.
=> CLI-531: Add docs command.

src/Command/Pull/PullCommandBase.php
**Motivation**
Fixes CLI-540
Only autoselect db if site name matches database name.
See CLI-540.
=> CLI-540: Only autoselect db if site name matches database name.

src/Command/Archive/ArchiveExportCommand.php, src/Command/CommandBase.php, src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, src/Command/Push/PushDatabaseCommand.php, src/Helpers/LocalMachineHelper.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php, tests/phpunit/src/Commands/Push/PushDatabaseCommandTest.php, tests/phpunit/src/Misc/EnvDbCredsTest.php, tests/phpunit/src/Misc/LandoInfoTest.php, tests/phpunit/src/Misc/LandoInfoTrait.php
**Motivation**
Allows multiple dbs to be pulled.
Add the `--multiple-dbs` option to the `acli pull:db` command.
3. Run `acli pull:db --multiple-dbs`
4. Run `acli pull:db`
5. Test in a Cloud IDE, in Lando, and on your native local machine.
=> Support pulling multiple dbs in Lando

src/Helpers/LocalMachineHelper.php
**Motivation**
Fixes IDE-557
If $HOME is not set and cannot be determined, throw an error.
=> Fixes #557: Throw error if $HOME cannot be determined.

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullFilesCommandTest.php
=> Remove disk space check.

src/Command/CommandBase.php
**Motivation**
Fixes #742
Throw an exception if no Cloud sites are detected.
=> Fixes #742: Fail gracefully when no Drupal installation is found.

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullFilesCommandTest.php
=> Fix files destination.

composer.lock
=> Update all Composer dependencies.

assets/acquia-spec.yaml
**Motivation**
Latest Cloud API spec.
Update spec.
=> CLI-597: Update Cloud API spec.

src/Command/Push/PushArtifactCommand.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php
**Motivation**
After some more thought, this is a property that should always be set "on the fly."
=> CLI-596: Remove destination-git-branch from .acquia-cli.yml.

composer.json, composer.lock, src/Command/Archive/ArchiveExportCommand.php, src/Command/ClearCacheCommand.php, src/Command/CommandBase.php, src/Command/NewCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Push/PushArtifactCommand.php, src/Command/Remote/AliasesDownloadCommand.php, src/EventListener/ComposerScriptsListener.php, src/Helpers/LocalMachineHelper.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php, tests/phpunit/src/Commands/Ide/Wizard/IdeWizardCreateSshKeyCommandTest.php, tests/phpunit/src/Commands/NewCommandTest.php, tests/phpunit/src/Commands/Pull/PullCodeCommandTest.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php, tests/phpunit/src/Commands/Remote/AliasesDownloadCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyCreateCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyCreateUploadCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyUploadCommandTest.php, tests/phpunit/src/Commands/TelemetryCommandTest.php, tests/phpunit/src/Commands/WizardTestBase.php, tests/phpunit/src/Misc/ApiSpecTest.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes #756
Replace webmozart/path-util with symfony/filesystem.
=> Fixes #756: Replace webmozart/path-util with symfony/filesystem.

src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
**Motivation**
Ensure that the cs:wizard's processes always execute in the correct IDE directory.
=> Execute cs:wizard commands inside /home/ide/project.

assets/acquia-spec.yaml
**Motivation**
Fixes #766
Update Cloud API spec.
=> Fixes #766: Incorrect required request parameter name for api:subscriptions:post-domain-registration endpoint.

composer.lock, tests/phpunit/src/CommandTestBase.php
Straight up `composer update`.
=> Composer update.

src/Command/Ssh/SshKeyCommandBase.php, src/Command/Ssh/SshKeyCreateUploadCommand.php
=> CLI-627: Fix ssh-key:create-upload.

src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
**Motivation**
Improve message.
Improve message.
=> Update one time push message for cs:wizard.

bin/acli, src/Command/CodeStudio/CodeStudioWizardCommand.php, src/Command/Push/PushArtifactCommand.php, src/Helpers/LocalMachineHelper.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
**Motivation**
* Prompts user to choose namespace for new projects when multiple are available
* Improve wording
* Warn when re-configuring an existing project
* Check for docroot rather than docroot/index.php
* Always add git remote
=> CLI-636: Improve UX of cs:wizard command.

src/Command/NewCommand.php, tests/phpunit/src/Commands/NewCommandTest.php
**Motivation**
Match Code Studio's default 
=> New command should set default git branch to main.

src/Command/Pull/PullDatabaseCommand.php
=> Run drush sql-sanitize after `pull:db`

composer.json, composer.lock
=> Update composer dependencies.

src/Command/CodeStudio/CodeStudioWizardCommand.php
=> Update Code Studio Wizard wording.

src/Command/CodeStudio/CodeStudioWizardCommand.php
=> Add git push instructions to cs:wizard.

.github/workflows/release-drafter.yml
Release Drafter app is deprecated, need to use the action
=> Enable Release Drafter action

composer.lock, symfony.lock
**Motivation**
Fixes composer install bug introduced in https://github.com/acquia/cli/pull/842/commits/e602d5420c768d258e0ff4cec292cadea32efe97
Apply updates, restore symfony.lock
=> Fix Symfony lock

src/Command/App/CopyCronTasksCommand.php, tests/phpunit/src/Commands/App/CopyCronTasksCommandTest.php
**Motivation**
Fixes #860
Rename `app` in `env` whenever possible.
N/A
* Try to run a copy task.
* Try to not pass any argument and see the error and suggestions.
=> Fix #860: app:cron-copy copies between envs not apps

.gitignore, .phplint.yml, composer.json, composer.lock, package-lock.json, phpcs.xml.dist, phpunit.xml.dist, symfony.lock
**Motivation**
Linting is oddly one of the slowest parts of our test suite.
Use parallel linting courtesy of https://github.com/overtrue/phplint
Also clean up configuration for our other dev dependencies
=> CLI-702: Parallel PHP linting

composer.json, composer.lock
**Motivation**
Fixes #661
Upgrade typhonius/acquia-logstream
See #661
=> Fix #661: Upgrade typhonius/acquia-logstream

src/Command/Ssh/SshKeyCommandBase.php
=> Raise timeout for SSH key deployment.

src/Command/Api/ApiCommandHelper.php, src/Descriptor/ReStructuredTextDescriptor.php, tests/phpunit/src/Commands/Self/MakeDocsCommandTest.php
=> Improve generated docs.

src/Command/DocsCommand.php, src/Helpers/LocalMachineHelper.php
=> Small improvements to docs command.

assets/acquia-spec.yaml
=> Update Cloud API spec.

.github/workflows/ci.yml
=> Trigger CI workflow when a release is created

.github/workflows/create-ccb-ticket.sh
=> Encode special chars for CCB ticket description.

.github/workflows/create-ccb-ticket.sh
=> Remove emojis from CCB ticket.

.github/workflows/ci.yml, .gitignore, composer.json, composer.lock, src/Command/Email/ConfigurePlatformEmailCommand.php, symfony.lock, tests/phpunit/src/Commands/Email/ConfigurePlatformEmailCommandTest.php
=> Revert "CLI-677: Fixes #834: For email:configure, add zone file as output format"

.gitignore, .phplint.yml, src/Descriptor/ReStructuredTextDescriptor.php
=> Improve make docs, again.

composer.json, composer.lock
=> Fixes #894: acli update should not update to pre-releases.

composer.json, composer.lock
=> Update typhonius/acquia-logstream to 0.0.12.

.github/workflows/create-ccb-ticket.sh, bin/acli, src/Command/CommandBase.php
=> Do not consider preleases to be available for update.

src/Command/Ide/IdeCommandBase.php, src/Command/Ide/IdePhpVersionCommand.php, src/Command/Ide/IdeXdebugToggleCommand.php, tests/phpunit/src/Commands/Ide/IdePhpVersionCommandTest.php, tests/phpunit/src/Commands/Ide/IdeXdebugToggleCommandTest.php, tests/phpunit/src/TestBase.php
=> Fixes CLI-652: Support xDebug for PHP 8.

src/Command/Api/ApiCommandBase.php
=> Fixes #907: api:applications:environment-create breaks if provides all arguments/options.

phpunit.xml.dist
=> Fixes #910: PHP warnings should cause tests to fail.

src/EventListener/ExceptionListener.php
=> Add help message when local config is invalid

src/Output/Spinner/Spinner.php
**Motivation**
Fixes #534: Checklists eat verbose output.
=> Fixes #534: Checklists eat verbose output.

src/DataStore/JsonDataStore.php
**Motivation**
Fixes #959
If `key` or `secret` are set, unset them and re-dump config.
Allow the `key` and `secret` keys.
3. Add a `key` key to `~/.acquia/cloud_api.conf`
4. Run `acli list` command.
5. Validate that no error is thrown.
6. Validate that `key` was removed from `~/.acquia/cloud_api.conf`.
=> Fixes #959: Unrecognized options "key, secret" under "cloud_api". Did you mean "keys"?

.gitignore, assets/acsf-spec.yaml, config/prod/services.yml, src/AcsfApi/AcsfClientService.php, src/Command/Acsf/AcsfListCommand.php, src/Command/Api/ApiBaseCommand.php, src/Command/Api/ApiCommandHelper.php, src/Command/Api/ApiListCommand.php, src/Command/Api/ApiListCommandBase.php, tests/phpunit/src/Commands/Acsf/AcsfApiCommandTest.php, tests/phpunit/src/Commands/Acsf/AcsfListCommandTest.php
=> Update ACSF specification.

src/Command/Api/ApiCommandHelper.php
=> Fix error when running phar.

config/prod/services.yml, src/Command/Acsf/AcsfApiAuthLoginCommand.php, src/Command/Acsf/AcsfApiAuthLogoutCommand.php, src/Command/Acsf/AcsfApiBaseCommand.php, src/Command/Acsf/AcsfCommandBase.php, src/Command/CommandBase.php
=> Move acsf:auth:* to auth:acsf-*

src/Command/App/EnvironmentMirrorCommand.php
**Motivation**
Fixes #990
Change from optional to required arguments.
=> Fixes #990: app:environment:mirror without arguments should not fail.

src/Command/App/EnvironmentMirrorCommand.php
**Motivation**
Fixes #989
Fix notification response.
=> Fixes #989: Fatal PHP error when using app:environment:mirror.

bin/acli, src/Kernel.php
=> Add support for ACLI plugins.

src/Command/App/DeleteCdeCommand.php, tests/phpunit/src/Commands/App/DeleteCdeCommandTest.php
=> Add app:environment:delete command.

src/AcsfApi/AcsfClient.php, src/AcsfApi/AcsfClientService.php, tests/phpunit/src/Commands/Acsf/AcsfApiCommandTest.php
3. `./bin/acli acsf:tasks:get`
=> CLI-768: Support array responses from ACSF.

src/Command/CodeStudio/CodeStudioCommandTrait.php, src/Command/CodeStudio/CodeStudioPipelinesMigrateCommand.php, src/Command/CodeStudio/CodeStudioWizardCommand.php, src/Command/CommandBase.php, src/Command/Ide/Wizard/IdeWizardCreateSshKeyCommand.php, tests/phpunit/src/Commands/Ide/Wizard/IdeWizardCreateSshKeyCommandTest.php
=> Check for required permissions before running `ide:wizard`.

assets/acsf-spec.yaml, composer.lock, src/Command/Api/ApiBaseCommand.php, src/Command/Api/ApiCommandHelper.php, tests/phpunit/src/Commands/Acsf/AcsfApiCommandTest.php, tests/phpunit/src/Commands/Acsf/AcsfListCommandTest.php
=> DG-26033: Add interactive support for boolean arguments.

src/Command/Api/ApiBaseCommand.php, tests/phpunit/src/CommandTestBase.php
=> Fix ACSF specification. 

src/Command/Api/ApiBaseCommand.php
=> DG-26035: Add support for array arguments.

assets/acquia-spec.yaml, src/Command/Api/ApiCommandHelper.php
=> Update spec to include Cloud Actions.

assets/acsf-spec.yaml
=> Update ACSF spec with required parameters.

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
=> Fixes #460: Try more domains when SSL cert in invalid.

src/Command/Api/ApiBaseCommand.php, tests/phpunit/src/Commands/Acsf/AcsfApiCommandTest.php
=> Fixes CLI-801: Certain ACSF commands don't accept passing multiple integers.

assets/acsf-spec.yaml
=> Update ACSF spec with latest fixes

.github/workflows/ci.yml
=> Catch Composer PSR issues

.env, .github/workflows/ci.yml, composer.json, composer.lock, symfony.lock
Apparently you need flex to run `composer dump-env`, which is used locally to generated `.env.local.php` which sets APP_ENV and APP_DEBUG, and in production to generate the compiled .env file for a (I think tiny) performance boost.
=> restore symfony flex

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, CONTRIBUTING.md
=> CLI-847: Attach acli.phar as GH artifact

src/Command/CommandBase.php, src/DataStore/Datastore.php
I had a bit of a brain fart and kept looking for this file in my home directory somewhere, I forgot it's project-local. Printing the full filepath would prevent confusion, and doing it directly from the datastore makes this future-proof.
=> CLI-856: Clarify .acquia-cli.yml filepath

composer.json, composer.lock, src/Command/Archive/ArchiveExportCommand.php, src/Command/Push/PushArtifactCommand.php, symfony-fs-mirror.patch, tests/phpunit/src/Commands/Archive/ArchiveExporterCommandTest.php
**Motivation**
Fixes #1162
Revert:
- https://github.com/acquia/cli/commit/9df38003e16268ff8067431fe5c5f31212ac6903
- https://github.com/acquia/cli/pull/1120
3. Follow testing steps from #1162
=> CLI-846: Restore symfony fs patch

src/Command/Ide/IdeCreateCommand.php
=> CLI-866: Fix PHP error on ide:create

assets/acquia-spec.yaml, src/Command/Api/ApiCommandHelper.php
**Motivation**
Fixes api:environments:log-create, which is accepting parameters incorrectly due to a bug in the API spec.
Update the API spec to include the new bug fix.
=> CLI-905: Fix api:environments:log-create

src/Command/CodeStudio/CodeStudioCommandTrait.php, src/Command/CodeStudio/CodeStudioPhpVersionCommand.php, src/Command/CommandBase.php, src/Command/Ide/IdePhpVersionCommand.php, tests/phpunit/src/Application/KernelTest.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioPhpVersionCommandTest.php
Issue - https://github.com/acquia/cli/issues/1297
=> Adding new command to update PHP version for code studio.

src/DataStore/Datastore.php, src/DataStore/JsonDataStore.php, src/DataStore/YamlStore.php, src/EventListener/ExceptionListener.php, tests/phpunit/src/Application/ExceptionApplicationTest.php
Unfortunately this exception is thrown early in the bootstrap process so we can't intercept and format it nicely using the exception listener.
=> CLI-925: Clean up invalid config exception

src/Command/App/AppVcsInfo.php, tests/phpunit/src/Application/KernelTest.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/App/AppVcsInfoTest.php, tests/phpunit/src/TestBase.php
Fix #1002
Old pull request which was closed - https://github.com/acquia/cli/pull/1003
=> Fix #1002: Adding new command to list details of the VCS branches / tags of an application

tests/phpunit/src/Commands/Env/EnvCopyCronCommandTest.php, tests/phpunit/src/Commands/Env/EnvDeleteCommandTest.php
Adding some more tests for the EnvCronCopy and EnvDelete command as when those command were added, I was struggling with writing test cases because of almost no knowledge of testing  :-). Now I have some confidence (though still learning) :)
=> Adding some test cases for the EnvCronCopy and EnvDelete command.

src/Command/Push/PushArtifactCommand.php
=> CLI-953: Fix push:artifact usage

box.json
https://github.com/box-project/box/pull/696
=> Add box.json schema

composer.json, composer.lock, src/Application.php
https://github.com/consolidation/self-update/pull/21
=> CLI-951: Unpatch consolidation/self-update

.github/workflows/ci.yml, .github/workflows/jira.yml
=> set issue label

composer.json, composer.lock
**Motivation**
Fixes #1418
If the same root cause continues to appear, we may need to roll back the acquia-php-sdk release entirely, or make all of the responses nullable irrespective of the spec.
=> CLI-992: Fix #1418: Job function is null

bin/acli, composer.json, composer.lock, src/Application.php, src/Command/CommandBase.php
Fix #1426
Upstream patch: https://github.com/consolidation/self-update/pull/25
=> CLI-995: Trailing zero in acli version

src/Command/Pull/PullCommandBase.php
=> getBackupPath error

src/Command/Pull/PullCommandBase.php, src/Helpers/IdeCommandTrait.php, src/Helpers/LocalMachineHelper.php
`file_get_contents(/home/ide/configs/php/.version): Failed to open stream: No such file or directory`
Reported via BugSnag.
=> IDE version file does not exist

src/Command/Pull/PullCommandBase.php
> AcquiaCloudApi\Endpoints\DatabaseBackups::getAll(): Argument #2 ($dbName) must be of type string, null given
> Attempt to read property "name" on bool
=> dbName must be of type string

src/Command/CommandBase.php, tests/phpunit/src/Commands/Acsf/AcsfAuthLoginCommandTest.php, tests/phpunit/src/Commands/Auth/AuthLoginCommandTest.php, tests/phpunit/src/Commands/Ide/IdeCreateCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyCreateUploadCommandTest.php
@anavarre do you want a chance to review this?
=> CLI-997: User input should have a CTA

src/Command/Ide/IdeListMineCommand.php
=> CLI-858: [ide:list:mine] accepts sitegroup param but doesn't use it

src/Command/CodeStudio/CodeStudioPhpVersionCommand.php
`CommandBase::getCloudApplication(): Argument #1 ($application_uuid) must be of type string, null given`
=> CLI-1036: [codestudio:php-version] null applicationUuid

.github/workflows/ci.yml, composer.json, composer.lock
Fix #1230 
Need workarounds from https://github.com/codecov/codecov-action/issues/837
Apparently variables not available in PRs: https://github.com/orgs/community/discussions/44322
Only option is to hardcode token. The [only risk is that someone could pollute our coverage data](https://github.com/codecov/codecov-action/issues/837#issuecomment-1453877750). Hey haxors, please don't do this 😄
=> Add codecov

composer.json, composer.lock, src/Command/Pull/PullCommandBase.php
https://github.com/typhonius/acquia-php-sdk-v2/pull/384
=> CLI-1046: Cannot assign null to DatabaseResponse::user_name

src/Command/Remote/SshCommand.php, tests/phpunit/src/Commands/Remote/SshCommandTest.php
=> CLI-1058: Fix remote:ssh

.github/workflows/ci.yml, bin/acli, box.json
I don't like relying on Box-specific features, and this one especially is problematic. It's hard to reason about and easy to screw up by using `@package_version@` where you shouldn't.
=> Set version from env file

.github/workflows/ci.yml, composer.lock
We'll keep the Jira ticket open to monitor the abandoned dependency and decide how to proceed.
=> CLI-1070: Abandoned packages

composer.json, composer.lock, phpcs.xml.dist
Fix #1401 
We'll keep a ticket open internally to add strict typing everywhere, but that's a huge lift
=> CLI-978: Upgrade coding standards

composer.json, composer.lock
I'm hoping downgrading guzzlehttp/promises fixes this: https://github.com/Kevinrob/guzzle-cache-middleware/issues/180
=> CLI-1083: Undefined array key request

composer.lock, src/Command/CommandBase.php, src/Command/Ide/IdeXdebugToggleCommand.php, src/Command/Ide/Wizard/IdeWizardCommandBase.php, src/Command/Ssh/SshKeyCommandBase.php, src/Command/WizardCommandBase.php, src/DataStore/Datastore.php, src/Exception/AcquiaCliException.php, src/Helpers/LocalMachineHelper.php, src/Helpers/LoopHelper.php, src/Helpers/TelemetryHelper.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Remote/AliasesDownloadCommandTest.php, tests/phpunit/src/TestBase.php
https://github.com/slevomat/coding-standard/issues/1589
=> CLI-1093: slevomat/coding-standard 8.13.1

src/Command/CommandBase.php
I'd prefer to strictly validate the git config file, but the syntax / schema isn't rigidly defined by Git itself. We could also use git commands to parse it, but that's probably overkill.
=> CLI-1104: Undefined array key url

.github/workflows/jira.yml
**Motivation**
Fixes #CLI-1157
Adds missing required parameters in the Jira workflow automation instrumentation. There is no impact on the end-user.
NA
1. Create a new issue in the repo, and check if a linked Jira ticket is automatically created in the [CLI](https://acquia.atlassian.net/browse/CLI) project.
=> CLI-1157: Fix Jira workflow

composer.json, composer.lock
https://github.com/typhonius/acquia-php-sdk-v2/pull/426
Cut a new release and return to stable before merging
=> CLI-1143: Don't use invalidated access keys

.github/workflows/ci.yml
=> CLI-1151: Support PHP 8.3 and 8.4

src/Command/CodeStudio/CodeStudioCiCdVariables.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioCiCdVariablesTest.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
PR : https://github.com/acquia/cli/pull/1683 is merged in acli main branch but there were few changes which were causing issues added fix for those in this PR.
@danepowell please review and merge this PR.
=> GL-2039-1: Fixed functionality and test cases for cs:wizard command.

infection.json5
=> CLI-1337: Ignore mutations for logger

src/Command/CommandBase.php
=> CLI-1347: Fix TypeError for null notificationUuid

composer.json, composer.lock
=> Switch to stable cache-plugin

src/Command/Api/ApiCommandHelper.php
=> CLI-1379: TypeError in api:environments:cron-create

src/Command/Push/PushArtifactCommand.php
**Motivation**
Fixes CLI-1378
Fixes #1782
=> CLI-1378: Multiple push:artifact remotes

.github/workflows/ci.yml, bin/acli, composer.json, composer.lock, src/Command/CommandBase.php, tests/phpunit/src/Application/KernelTest.php, tests/phpunit/src/ApplicationTestBase.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes CLI-1392
Fixes #1792 
https://github.com/consolidation/self-update/pull/35
=> CLI-1392: Redundant version notifications

composer.json, composer.lock
**Motivation**
Fixes CLI-1452
Fork Bugsnag: https://github.com/bugsnag/bugsnag-php/pull/671
=> CLI-1452: PHP 8.4 compatibility (bugsnag)

composer.json, composer.lock
=> CLI-1447: Unfork packages for PHP 8.4

.github/workflows/ci.yml
=> Add commit SHA to dev build versions

composer.json, composer.lock
=> CLI-1465: grumphp stable release

src/Helpers/TelemetryHelper.php
**Motivation**
Fixes CLI-1493
- Replace Amplitude key (in GitHub secrets) after migrating to new project
- Fix regression since 2.30 that prevented any data being sent 😢 https://github.com/acquia/cli/pull/1806
=> CLI-1493: Rotate amplitude key

composer.json, composer.lock, tests/phpunit/src/Commands/CodeStudio/CodeStudioPhpVersionCommandTest.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioPipelinesMigrateCommandTest.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
=> CLI-1463: Unfork php-gitlab-api

composer.json, composer.lock
=> CLI-1510: PHP 8.4 deprecation warning in ratchet/rfc6455

tests/phpunit/src/Misc/ApiSpecTest.php, tests/phpunit/src/Transformer/EnvironmentTransformerTest.php
=> PIPE-6969: [Non Prod]Replace references to CX Network Domains with ACN Domains

.github/workflows/build-spc.yml, bin/acli, composer.json, var/craft.yml
=> CLI-1484: Native binaries
