.travis.yml
When we made the repo public, Travis CI [stopped injecting SSH keys](https://docs.travis-ci.com/user/private-dependencies/#user-key) into the build container. This in turn caused the ssh-agent not to start, so we need to [start it ourselves](https://github.com/travis-ci/travis-ci/issues/3652).
=> Fix travis test failures due to missing ssh-agent

composer.json, composer.lock, symfony.lock
Fixes #112 
The php version in symfony.lock keys off of `config.platform.php`: https://github.com/symfony/flex/issues/609
=> Fix php version in symfony.lock

bin/acli, config/services.yml
After getting a release out, we should refactor find_repo_root to be a static method, maybe on LocalMachineHelper, and add unit tests.
Also then set it using an Expression in services.yml rather than via the acli bin.
Generally, we need to get stuff out of the acli bin so we can test it. Almost all of the instability following the DI conversion is due to stuff in there.
=> Fix #111: Detect repo root correctly.

src/Command/Api/ApiCommandBase.php, tests/phpunit/src/TestBase.php
I've confirmed this shows up in Sumo Logic as "acli/@package_version@" (with a real version for a phar release)
Also talking about setting a default user agent for the SDK: https://github.com/typhonius/acquia-php-sdk-v2/issues/73
=> Set user agent string

CONTRIBUTING.md, src/Command/UpdateCommand.php
Fix #218 
This error occurs when any class is lazy-loaded after the update runs. The simplest solution is to immediately terminate the script after an update.
An alternative solution would be to preload telemetry classes so that telemetry reports during successful self-update commands. But that gets a little hairy: we risk this bug recurring if we introduce any new classes and forget to preload them as well.
=> Fix #218: Self-update errors

box.json, box.json.md
Fix #219
I don't know exactly why we disabled requirement checking originally. I think just because "that's what the Symfony template did".
I tested and this seems to work fine with requirements checking in place.
Note that previously you _could_ run _parts_ of ACLI with PHP 7.2 or without the php-json extension installed, and only certain commands would fail. Now you will not be able to run ACLI at all under those conditions.
=> Fix #219: Enforce PHP version requirements

composer.json, composer.lock, symfony.lock
Acquia is potentially changing the value AH_SITE_ENVIRONMENT in IDEs from `IDE` to `ide`. A new version of the environment detector supports this: https://github.com/acquia/drupal-environment-detector/releases/tag/v1.1.1
=> Support Cloud IDE AH_SITE_ENVIRONMENT rename

.travis.yml, bin/acli, composer.json, src/Command/CommandBase.php, src/Command/UpdateCommand.php
Fix #234 
According to the [humbug/phar-updater docs](https://github.com/humbug/phar-updater#avoid-post-update-file-includes), we need to do one of two things to avoid post-update errors:
1. Exit immediately after updating
2. Pre-load any classes that might be used after updating
We chose to exit immediately in #220, which is simple and safe (for the end user) but unfortunately breaks PHPUnit tests.
This PR takes the approach of exiting as soon as possible (though not immediately, since we can't force Symfony to quit any sooner than this), and pre-loading classes that we know Symfony needs before it exits. It's kind of ugly but unavoidable.
The only other solutions I can think of, even uglier I think:
- Stop testing for successful self-updates
- Use a mockable class to exit the command …
=> Fix #234: self-update command aborts tests

src/Command/RefreshCommand.php, tests/phpunit/src/Commands/RefreshCommandTest.php
Fixes #227  
--------
Motivation
----------
#227 describes an error when running `acli refresh` for ACSF sites. I believe this to be a regression caused by https://github.com/acquia/cli/pull/74 . This caused SSH command output to be printed to the screen, which apparently also prevents `$process->getOutput()` from capturing it.
---------
Suppress SSH command output, so it can be captured programmatically. This is ideal for the human (who doesn't need to see a bunch of gobbledygook), and also fixes the error.
---------
- Change the default for [SshHelper::executeCommand()](https://github.com/acquia/cli/blob/v1.0.0-rc6/src/Helpers/SshHelper.php#L40) to _not_ print output. @joazvsoares @imnetworku do you have an opinion on this? Most places in the …
=> Fix #227: Errors refreshing ACSF site

composer.json, composer.lock, src/Command/Ide/Wizard/IdeWizardCreateSshKeyCommand.php
Fixes #228  
--------
Motivation
----------
See #228 
---------
Use the environment detector to detect a dev environment rather than looking for a hardcoded string ('dev').
---------
Copying the regex or hardcoded dev environment names from the environment detector... silly :smile: 
Testing steps
---------
Apply this PR as a patch, run `ide:wizard:ssh-key:create-upload` against an ACSF subscription, verify that notices are gone
@anavarre can you please test and verify this fixes the issue for you?
=> Fix #228: PHP notice creating SSH key on ACSF

src/Command/Api/ApiCommandBase.php, src/Command/Api/ApiCommandHelper.php
Fixes #247 
--------
Motivation
----------
See #247. Running `acli help api:environments:update` results in an error because version is defined both via the CLI and API.
---------
This renames the API `--version` to `--lang_version`.
---------
If this becomes a pattern with other parameters, we might want a full translation layer that renames conflicting parameters either automatically (if it detects a conflict) or statically (based on hardcoded mappings). Or at least use a constant utility class between the API command base and helper.
Testing steps
---------
- Run `acli cache:clear`
- Run `acli help api:environments:update`.
@eporama if you're comfortable running dev builds, you're welcome to test.
=> Fix #247: Rename api:environments:update --version parameter

src/EventListener/ExceptionListener.php
Motivation
----------
When the Acquia Cloud SDK throws an exception because the API returned an error, it _looks_ like the error is coming from Acquia CLI. This leads to support requests directed to Acquia CLI that really should be directed to Cloud API.
---------
Prepend the exception with more informative text. Before and after:
---------
Instead of modifying the exception we could:
- Add text outside of the exception instead of modifying it. This is less cluttered but perhaps also visible. and/or:
- Exit cleanly without throwing an exception at all (but still returning a non-zero exit code) so it's a little less scary.
Testing steps
---------
`./bin/acli ide:create --cloud-app-uuid 2ed281d4-9dec-4cc3-ac63-691c3ba002ca` (this is an invalid UUID) …
=> DX-2334: Indicate when errors come from Cloud API

composer.json, composer.lock, phpcs.xml.dist, symfony.lock
This removes four of the warnings on composer installs by [updating drupal/coder](https://www.drupal.org/node/3116414) and also removing phpcs-security-audit in accordance with ORCA, since phpcs-security-audit is abandoned:
- https://github.com/acquia/coding-standards-php/pull/13
- https://github.com/FloeDesignTechnologies/phpcs-security-audit/issues/78
=> Remove deprecation warnings on composer install

src/Command/CommandBase.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php
Motivation
----------
The filter query for `getApplicationFromAlias` carries through to future client requests in the same execution. It should be removed before proceeding.
---------
This adds a `clearQuery()` to the script after retrieving the application information
---------
Build a separate client connection (too cumbersome)?
Testing steps
---------
```
bin/acli api:applications:database-list <app_name>
```
returns this error before the patch
```
{
"error": "invalid_filter",
"message": "Invalid filtering option supplied hosting. Supported filters are: name"
}
``` 
and returns a list of databases for the application after.
=> DX-2482 | Fix to clear client query filter

composer.json, src/Command/Api/ApiCommandBase.php, src/Command/CommandBase.php, src/Command/Ide/IdeCommandBase.php, src/Command/LogTailCommand.php, src/Command/RefreshCommand.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php, tests/phpunit/src/Commands/CommandBaseTest.php, tests/phpunit/src/Commands/LogTailCommandTest.php
Functional changes:
* log:tail now accepts aliases like `@eemgrasmick.dev`
* link now accepts aliases like `@eemgrasmick.dev`
* ide:* commands now accept aliases with and without `@` prefix
* remote:aliases:list will now accept an alias for the applicationUuid argument
=> Accept application and environment aliases.

src/Command/Pull/PullCodeCommand.php, src/Command/Pull/PullCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, src/Command/Pull/PullFilesCommand.php, src/Command/Remote/AliasesDownloadCommand.php, tests/phpunit/src/Commands/Pull/PullCommandTest.php
No functional changes at all, just a rename of `refresh` to `pull:all` (with aliases to `refresh` and `pull`) and a few new non-functional stubs.
This does prep work for #201, which will introduce `push:*` commands.
=> Rename refresh command to pull. Create pull sub command stubs.

src/Command/CommandBase.php, src/Command/Ide/IdeCreateCommand.php, src/Command/Ide/IdeDeleteCommand.php, src/Command/Ide/IdeListCommand.php, src/Command/Ide/IdeOpenCommand.php, src/Command/LinkCommand.php, src/Command/LogTailCommand.php, src/Command/Remote/AliasListCommand.php
Motivation
----------
Most commands have no usage examples except for those automatically generated by Symfony for each argument. It's not clear to users, for instance, that they can use either an application UUID or sitegroup alias for any command with an app UUID argument.
---------
Instead of manually adding app / environment ID arguments and usage examples to every command individually, encapsulate these in a common method. See before and after examples for the two commands refactored so far:
---------
Write the usage example for each command individually. That's a lot of unnecessary repetition.
Testing steps
---------
Run `acli help link` or `acli help log:tail`.
@grasmash @anavarre are you okay with this general approach? If so I'll finish …
=> DX-1605: Add usage examples

src/Command/Auth/AuthLoginCommand.php, src/Command/Auth/AuthLogoutCommand.php, src/Command/CommandBase.php, src/Command/Ide/IdeCreateCommand.php, src/Command/Ide/IdeDeleteCommand.php, src/Command/NewCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Push/PushDatabaseCommand.php, src/Command/Push/PushFilesCommand.php, tests/phpunit/src/Commands/NewCommandTest.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php, tests/phpunit/src/Commands/Push/PushDatabaseCommandTest.php
Motivation
----------
We received product feedback from @ba66e77 that the confirmation questions asked by Acquia CLI are confusing because they don't tell you what the available/default responses are (y/n/yes/no/whatever). For the record, Symfony basically interprets anything starting with a "y" as "yes", but being more explicit can't hurt.
---------
Switch from the Symfony question helper to the higher-level style component, which automatically formats confirmation questions to include suggested and default responses.
This has the effect of changing how questions are formatted.
Before:
After:
---------
Keep using the lower-level question helpers and manually modify each invocation to add y/n and defaults.
Testing steps
---------
Run any command …
=> DX-2533: Added confirmation question prompt and default responses

src/Command/Ide/Wizard/IdeWizardCreateSshKeyCommand.php
This is a total guess. No idea if it actually fixes the issue.
=> Fixes #316: SSH key wizard often returns duplicated info on screen.

tests/phpunit/src/TestBase.php
@grasmash you opened this ticket, this might be halfway to a solution but I'm not quite sure where to take it from here.
I understand from an aesthetic perspective why having one input/output pair defined on the test base and another defined in each command is ugly, but functionally I don't see the problem.
The best solution I see is to set a default intput/output during setup (to populate all of the helper objects), and then reset them if necessary per test case. So for instance, the TelemetryCommandTest could call `setIo($new_input, $new_output)`.
But I guess I don't understand what you win here. It doesn't look like the Symfony Command tester even uses an actual input stream, it only takes a simple array.
Let me know what you want to do with this.
=> DX-1752: Use single input/output objects for testing

tests/phpunit/src/Commands/Ide/IdeCreateCommandTest.php, tests/phpunit/src/TestBase.php
Motivation
----------
Kept getting this error running tests locally:
> 1) Acquia\Cli\Tests\Commands\Ide\IdeCreateCommandTest::testCreate
array_map(): Expected parameter 2 to be an array, null given
Seemed to be a bit of a heisenbug, it would come and go on different machines. I've never seen it in Travis CI, not sure why. Maybe there's an actual network call happening here? :grimacing: 
---------
Mock environment requests for all applications in this test. This is necessary because the command loops through all applications, but we only mock the first one:
- https://github.com/acquia/cli/blob/1.0.0/src/Command/CommandBase.php#L488
- https://github.com/acquia/cli/blob/1.0.0/tests/phpunit/src/TestBase.php#L440
---------
I have no idea why this only …
=> Fix heisenbug in IDE create test

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
Motivation
----------
Fixes #242
---------
Upon a DB pull, copy the default db settings file to match the name of the pulled db.
---------
Tons, see #242 
Testing steps
---------
`acli pull:db` on a multisite app, ensure that a new file is created at `/var/www/site-php/[sitegroup]`
=> Fix #242: Support multisite db refresh

.coveralls.yml
Motivation
----------
I don't think this file is necessary to run Coveralls via Travis CI.
---------
Remove the file.
Testing steps
---------
Just make sure Coveralls still runs and reports on this PR.
=> DX-2657: Remove coveralls config

src/Command/Remote/DrushCommand.php, src/Command/Remote/SshCommand.php
And a small fix for remote:drush for consistency
Motivation
----------
SSH Help text implies that you can pass a command, however the command is only meant for opening an interactive session
Also, remote:drush uses the incorrect terminology `<site>.<env>` which is inconsistent.
---------
Just help text on two commands
Testing steps
---------
Run `help remote:ssh` and make sure it makes sense
Run `help remote:drush` and make sure it doesn't mention `<site>`.
=> Updated help text for remote:ssh

src/Command/Ide/IdeInfoCommand.php, tests/phpunit/src/Commands/Ide/IdeInfoCommandTest.php
@anavarre before I add tests, how do you feel about this?
=> DX-1669: Add ide:info command

src/EventListener/ExceptionListener.php, tests/phpunit/src/Application/ExceptionApplicationTest.php
Motivation
----------
The Cloud API error message indicates when no IDEs are available, but doesn't indicate how to resolve this.
---------
Suggest users delete an existing IDE or purchase more
---------
Fix the message upstream in Cloud API
Testing steps
---------
3. Run `acli ide:create` on an application with no available IDEs.
=> DX-1780: Better message when no IDEs available

src/Command/CommandBase.php, src/Command/Pull/PullCodeCommand.php, src/Command/Pull/PullCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, src/Command/Pull/PullFilesCommand.php, src/Command/Pull/PullScriptsCommand.php, src/Command/Push/PushDatabaseCommand.php, src/Command/Push/PushFilesCommand.php, tests/phpunit/src/Commands/Pull/PullCodeCommandTest.php
Using the environmentId argument name allows users to use either an alias or a uuid.
=> Replace --cloud-env-uuid option with environmentId arg.

src/Command/Ide/IdeXdebugToggleCommand.php, tests/phpunit/src/Commands/Ide/IdeXdebugToggleCommandTest.php
Motivation
----------
@wimleers expressed some confusion that Xdebug wasn't automatically listening after running this command. Documentation is the easiest short-term solution.
---------
Notify customers they must also enable listening in the IDE.
---------
Automatically enable listening. Here be dragons though ("I tried to run Composer and it hung indefinitely...")
Testing steps
---------
3. Run `acli ide:xdebug` and see the help text.
=> Clarify xdebug usage

src/Command/CommandBase.php
I was confused reviewing https://github.com/acquia/cli/pull/355 because I recalled exempting commands from authentication via the base `commandRequiresAuthentication` method. Since `auth:login` already overrides `commandRequiresAuthentication` it should return TRUE by default, and point people to overriding it as the correct way to exempt commands.
https://github.com/acquia/cli/blob/40085f651405f7af6bcfed057ab2c715892014c7/src/Command/Auth/AuthLoginCommand.php#L39-L41
=> Tiny refactor: commandRequiresAuthentication

src/Command/Ide/IdeShareCommand.php
Motivation
----------
Fixes #354
You should be able to share your IDE code without having to be authenticated against the Cloud Platform API. If you're in your IDE, it means you've already successfully authenticated against the Acquia SSO portal, so there's no inherent security risk to doing this.
---------
Do not require `acli ide:share` to be authenticated against the Cloud Platform API
---------
Status quo
Testing steps
---------
3. Run `acli ide:share` …
=> Do not require authentication for ide:share command

src/Command/CommandBase.php
To aid in debugging issues like https://github.com/acquia/cli/issues/356 where we have debug logs, it would help to know the Acquia CLI version since people often fail to report it independently.
=> Print version for debugging

src/Command/CommandBase.php
When developing on ACLI you get an update notification on every command because of the placeholder version string.
=> Disable update notifications in development

src/Command/Remote/SshCommand.php
Motivation
----------
@eporama requested the ability to run custom commands via `remote:ssh`
---------
Add the ability to pass custom commands. If no command is provided, default to the old behavior (open a shell).
Testing steps
---------
3. Run `acli remote:ssh myapp.dev` to ensure the original behavior still works.
4. Run `acli remote:ssh myapp.dev -- ls -al` or any other command to see that it gets executed via SSH.
=> DX-2641: Allow passing SSH commands

src/Command/Ide/IdeCreateCommand.php
Motivation
----------
This solves user-end expectations `ide:create` for the server-side status-quo.
---------
The timeout for IDE creation is now in line with the server-side API soon to be released.
---------
We're working on more structural fixes for the middle-long term.
Testing steps
---------
=> DX-2794 | Increase timeout for IDE creation from 30 to 45 minutes

tests/phpunit/src/Commands/CommandBaseTest.php, tests/phpunit/src/Misc/ApiSpecTest.php, tests/phpunit/src/Misc/LandoInfoTest.php, tests/phpunit/src/Misc/LocalMachineHelperTest.php
Motivation
----------
Running `composer install` generates warnings:
> Class Acquia\Cli\Tests\ApiSpecTest located in ./tests/phpunit/src/Misc/ApiSpecTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Acquia\Cli\Tests\LocalMachineHelperTest located in ./tests/phpunit/src/Misc/LocalMachineHelperTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Acquia\Cli\Tests\LandoInfoTest located in ./tests/phpunit/src/Misc/LandoInfoTest.php does not comply with psr-4 autoloading standard. Skipping.
---------
Fix the namespaces
=> Fix test namespaces

config/services.yml, src/Helpers/ClientService.php
Motivation
----------
We re-use the Acquia Cloud API client across multiple requests, which probably isn't good because we directly modify the client query and options in commands. This means that queries/options from one Cloud API call could bleed into the next, even across different commands. We have seen odd behavior from the Cloud API client that could be attributable to this, though I don't know for sure.
---------
- Use a Client factory pattern as recommended in the acquia-php-sdk-v2 docs instead of re-using a single client
- Fix autowiring so that we can greatly simplify the ClientService class
---------
We could probably get rid of the ClientService completely, but it's still useful to facilitate testing. If we got rid of it, then we'd use …
=> DX-3045: Don't reuse AcquiaCloudApi client

src/Command/Pull/PullCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, src/Command/Pull/PullFilesCommand.php, tests/phpunit/src/Commands/Pull/PullCommandTestBase.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php, tests/phpunit/src/Commands/Pull/PullFilesCommandTest.php
Motivation
----------
Acquia CLI generates a new per-site db settings file during `pull:db`. Cloud IDEs now have a server-side script that does this for _every_ site, plus sets up file directories. Acquia CLI should delegate to the Cloud IDE script instead of managing the settings itself.
---------
- Run the IDE script rather than generating files individually
- Run the script as part of `pull:files` (previously only ran during `pull:db`)
- Make sure the script only runs once per command, and run it _before_ the rest of the command (previously it ran after), since at some point we might support multi-dbs and need those db in place before pulling them.
---------
There's probably a way to run this script singly as part of a pre-command or event hook …
=> DX-3061: Generate multisite settings and files for pulls

.github/release-drafter.yml
Motivation
----------
Creating release notes consistently is a pain
---------
Use https://github.com/release-drafter/release-drafter to automatically generate release notes based on PR labels:
- Breaking / major changes (major version increment)
- Enhancements (minor version increment)
- Bug fixes (patch version increment)
New releases will be kept in a draft state and constantly updated with new PRs until a human publishes them.
---------
We could split control of the issue type and severity. So have enhancement / bug labels in addition to major / minor / patch labels for direct control over versioning.
Testing steps
---------
I don't think this can be tested until it's merged 🤷
=> DX-2557: Enable release drafter

src/Command/CommandBase.php
Motivation
----------
Because Cloud IDEs are behind a NAT and share external IPs, if a bunch of users all run `acli self-update` within a 60-minute interval it can hit Github API rate limits.
---------
Disable update notifications so we aren't actively encouraging people to self-update at the same time when a new release comes out. They can still choose to self-update, or wait for the next platform release when ACLI is updated.
---------
Completely disable self-updates, or make the self-update command hidden in Cloud IDEs. I'd rather take a gentler approach to start.
Ideally we could provide a Github API key somehow, but consolidation/self-update doesn't support it.
=> DX-3073: Disable update notifications in Cloud IDE

src/Command/Api/ApiCommandHelper.php, src/Command/CommandBase.php, src/Helpers/TelemetryHelper.php, symfony.lock, tests/phpunit/src/Commands/Api/ApiCommandTest.php, tests/phpunit/src/Commands/Api/ApiListCommandTest.php, tests/phpunit/src/Commands/TelemetryCommandTest.php, tests/phpunit/src/TestBase.php
Motivation
----------
Fixes #366
---------
Use Amplitude consistently as a [singleton service](https://github.com/zumba/amplitude-php#zumba-amplitude-php) so that exceptions are reported correctly.
---------
Use Amplitude as an object or Symfony service, and pass it everywhere it's needed (including the exception). I don't know how to do this in a clean way.
Testing steps
---------
3. Remove your API credentials
4. Run a command requiring authentication …
=> DX-2994: Fix #366: Log exceptions

src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, tests/fixtures/backups_response.json, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Pull/PullCommandTestBase.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
This isn't quite complete (needs tests, code style cleanup) but it should be functional. I wanted to get it up before the long US weekend for initial feedback.
Instead of downloading db backups via MySQL dumps and SSH, this creates an on-demand backup via the Cloud API and then downloads the backup.
This is awesome because it's safer and allows more granular permissioning (no more SSH access to prod! 😬 ), but has two potential gotchas:
- It's a bit slower, because we have to wait for the notification api to tell us that the backup is ready.
- It's not deterministic, in that we have no way to ensure we are downloading the backup _we_ just created, since the notification API does not provide a backup ID. Instead, we just download the most recent backup on the assumption that it's ours.
=> DX-1682: Download db backups via API rather than SSH

composer.lock, symfony.lock
Motivation
----------
Fixes #393
---------
Update Amplitude to accommodate https://github.com/zumba/amplitude-php/pull/28
Now if the curl extension is missing, you get a more informative error prior to ACLI running:
Testing steps
---------
3. Build the phar (you cannot test this from source since it relies on Box dependency checking)
4. Run the phar in Windows without php-curl enabled and verify the error output is as above.
=> DX-3196: More helpful error message if curl is missing

.travis.yml
Motivation
----------
Our tests take an extra minute or two to run on Windows due to Composer packages not being cached.
---------
Hopefully speed up tests by caching these files on Windows like we do for Linux.
Testing steps
---------
This can't be tested until it's merged, since Travis CI won't modify a cache except as part of the master branch. I'll follow-up after merging to make sure it works.
=> Cache Composer for Windows tests

src/Command/Auth/AuthLoginCommand.php, src/Helpers/ClientService.php
Motivation
----------
Fixes #403
---------
auth:login should re-initialize the Typhonius Connector client service with the new credentials (otherwise it will use whatever was read at the start of the process)
This normally is not a problem since invoking one ACLI command in another is rare. `ide:wizard` is the only command I could find that invokes `auth:login`.
Testing steps
---------
3. Clear your Acquia credentials
4. Run `ide:wizard`
=> Fix #403: Commands that invoke auth:login fail to pick up new credentials

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullCodeCommandTest.php
Motivation
----------
pull:code checks out the matching branch from a remote env when updating an existing repo, but not when cloning a repo.
---------
Bring parity between fetching and cloning repos by checking out the matching branch when cloning as well.
Testing steps
---------
3. Run `acli pull:code` in an empty directory and choose a remote environment. Ensure that the matching branch is checked out locally.
=> DX-3178: Check out branch from remote environment on pull:code clone

.travis.yml
An unfortunate follow-up to #402 . It turns out that all of our caching in Travis (across Linux and Windows) actually _slows down_ builds, paradoxically. Composer 2 is so efficient that caching doesn't benefit it much, and Travis burns a lot of CPU time unpacking and repacking the cache. So let's just stop caching and remove some complexity.
For comparison:
- With caching, total time 8 minutes: https://travis-ci.com/github/acquia/cli/builds/215155409
- Without caching, total time 7:41: https://travis-ci.com/github/acquia/cli/builds/215155701
You can verify whether the cache was used and see its effect by looking at the "composer install" build step. The times are basically identical between builds, but in the cached one you can see that it skips downloading packages.
=> DX-3307: Remove Travis CI caching

.travis.yml
Note that curl is involved two ways here: we first use it to download cacert.pem so that PHP can later call curl. It's the second (PHP) call that was visibly failing, but the reason is that the first one (downloading the CA cert) failed silently.
It looks like the curl maintainers recently added a redirect from curl.haxx.se to curl.se. Curl doesn't follow redirects by default, resulting in a corrupt cacert.pem.
I considered adding a sha256 verification of cacert.pem so at least it wouldn't fail silently next time, but it seems like unnecessary complexity given that the sole purpose would be to accelerate debugging (and now that we've seen this error we can search for it in GH / Jira).
I also linked a follow-up ticket in Jira since our test cases shouldn't be making network calls in the …
=> Fix Travis CI tests (curl failure)

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullFilesCommandTest.php
Motivation
----------
Fixes #392 
Testing steps
---------
3. Run `acli pull:files`
4. Choose a multisite and ensure that files are placed in the multisite directory rather than `default`
=> Fix #392: pull:files multisite support

src/Command/Auth/AuthLoginCommand.php, src/Command/Auth/AuthLogoutCommand.php, src/Command/CommandBase.php, src/Command/Ide/IdeCommandBase.php, src/Command/Ssh/SshKeyDeleteCommand.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php, tests/phpunit/src/Commands/Auth/AuthLoginCommandTest.php, tests/phpunit/src/Commands/Auth/AuthLogoutCommandTest.php, tests/phpunit/src/Commands/TelemetryCommandTest.php, tests/phpunit/src/TestBase.php
User Experience:
1. User runs `acli login`
a. If no keys are saved locally, prompt to enter new key.
b. If keys already exist locally, prompt user to choose among existing keys or create a new key.
i. If selected existing key, set it as the default key for ACLI.
ii. If create new key, prompt to enter new key.
2. User runs `acli logout`
a. Unset the default key for ACLI, but do not remove the key from the filesystem.
This PR includes an automated migration path.
=> Fixes #339: Store multiple Acquia Cloud tokens in local file.

src/Command/Pull/PullCommandBase.php
We initially disabled this to prevent a negative impact to prod servers. As of https://github.com/acquia/cli/pull/396, this should no longer be a concern.
=> DX-3453: Include Production Environment as an option when copying from Cloud Platform.

src/Helpers/CloudCredentials.php
Currently, key's created in ACLI < 1.6.0 are not properly inserted into the services container. This PR resolves that issue.
=> Support legacy API keys.

src/Command/Pull/PullCodeCommand.php, src/Command/Pull/PullCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullScriptsCommand.php, tests/phpunit/src/Commands/Pull/PullCodeCommandTest.php, tests/phpunit/src/Commands/Pull/PullScriptsCommandTest.php
**Motivation**
Fixes #398
For pull commands, change the `dir` argument to an option. This is a breaking change for customers that were previously using the `dir` argument, but not severe enough that it warrants a major version bump I think.
3. Run `acli pull environmentId=foo` and `acli pull environmentId=foo --dir=bar` to make sure the command works with and without the dir argument.
=> Fix #398: [pull] Change dir argument to option

.travis.yml, composer.lock
**Motivation**
Fixes #437
https://github.com/composer/composer/releases/tag/2.0.10
> Fixed autoloader registration when plugins are loaded, which may impact plugins relying on this bug (if you use symfony/flex make sure you upgrade it to 1.12.2+ to fix dump-env issues)
- Test builds as part of PRs and nightly tests to catch this sooner next time
- Run `composer update` to fix the original bug
Verify the first commit (with just the test) fails. Second commit (with composer update) should pass.
=> Phar not generated for 1.7.1

src/EventListener/ExceptionListener.php
=> Fixes #434: Override the spec to better set expectations when an IDE is going to be deleted.

src/EventListener/ExceptionListener.php
=> Fixes #431: Make it obvious you can pass a sitegroup.env every time you can pass an environment ID.

src/Command/Ide/IdeCreateCommand.php, tests/phpunit/src/Commands/ChecklistTest.php
**Motivation**
Fixes #445
Right now, we're checking for a 200 at the `/health` endpoint. This _assumes_ we're waiting for DNS propagation to reach the end user. But in reality, DNS propagation usually happens fairly quickly and it's the queue processing times that can take time. Additionally, with IDE pre-provisioning, DNS propagation times will no longer be an issue. Instead, we'll be returning a different response code (503) until the IDE has its UUIDs pre-configured. We need to reflect this in the message.
More importantly, what matters is that we don't let people wait forever without setting expectations. We know it can take up to 15mn for the queue to be processed, so by giving this indication to our customers we're also making the wait time less painful. Often, it'll be faster than …
=> Better set expectations when a pre-provisioned IDE is going to be available

src/EventListener/ExceptionListener.php
As of 1.8.0, if a user tries to run an non-existent command like `acli fake-command` an exception will be thrown rather than showing the correct error output:
```
Fatal error: Uncaught Error: Call to a member function getApplication() on null in phar:///private/tmp/acli.phar/src/EventListener/ExceptionListener.php on line 77
Error: Call to a member function getApplication() on null in phar:///private/tmp/acli.phar/src/EventListener/ExceptionListener.php on line 77
Call Stack:
0.0856    1649144   1. {main}() /private/tmp/acli.phar:0
0.1502    1980968   2. require('phar:///private/tmp/acli.phar/bin/acli') /private/tmp/acli.phar:14
0.5803   16775344   3. Acquia\Cli\Application->run(???, ???) phar:///private/tmp/acli.phar/bin/acli:86
0.5983   16782488   4. Acquia\Cli\Application->doRun(???, …
```
=> Do not show help text for invalid commands.

.gitignore, CONTRIBUTING.md, RELEASE.md, composer.json
- Add build steps to contributing doc
- Remove release doc, since release drafter manages everything now
- Move box.phar to build directory so it's more easily excluded from Git and IDE indexing
These steps are necessary to test the fix for https://github.com/consolidation/self-update/issues/9 via https://github.com/danepowell/self-update/pull/3
=> Updated build and release docs

src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
**Motivation**
Currently, the `pull:db` command uses the latest periodic backup. This is undesirable in two cases:
1. If the environment has no backups (this is especially likely for ACSF dev environments)
2. If the customer wants a more recent backup
Support using an on-demand backup under two conditions:
1. Automatically, if there are no existing backups available
2. Manually, if requested via the `--on-demand` option
3. Run `acli pull:db` in scenarios …
=> [pull:db] Allow on-demand backups

src/Command/NewCommand.php, tests/phpunit/src/Commands/NewCommandTest.php
**Motivation**
Fixes #427
Check for existing `.git` repo before initializing one of our own.
Set dummy Git credentials or otherwise deal with missing Git creds in Cloud IDEs. This is the ideal solution, but requires a lot more work (see example implementation in BLT).
3. Run `acli new` in a Cloud IDE with the recommended project template and verify there are no errors.
=> DX-3486: [new] fails for existing git repo

src/Command/CommandBase.php, src/Command/Ide/IdeCommandBase.php, src/Command/NewCommand.php, src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php, tests/phpunit/src/Commands/Pull/PullFilesCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyDeleteCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyUploadCommandTest.php
**Motivation**
It's annoying to not have a default response to prompts, _especially_ when there's only a single available option.
Ensure every prompt has a default response, even if it's just the first option in whatever array of choices we present.
Wrap the Symfony `choice()` method in a utility class/method that ensures that every choice has a default even if it's not explicitly set. Seems like overkill.
3. Try commands like `acli new` or `acli pull:db` that force a selection from a list, and …
=> Ensure every prompt has a default response

composer.json
**Motivation**
Fixes #496
Pin the Box version and add the curl `--fail` flag so the script will exit and alert us next time instead of failing silently. Also update the namespace (apparently the project changed ownership).
Switch to something other than Box that can be properly verified. These have been known issues for a while with no maintainer response:
- https://github.com/box-project/box/issues/487
- https://github.com/box-project/box/issues/530
1. See that the first commit fails (as it should, since Box master is broken)
2. See that the second commit passes (after pinning Box to known good release)
=> Fix #496: Deploy builds failing

.travis.yml
**Motivation**
We regularly need to enlist the help of people less familiar with the ACLI codebase to test PRs or HEAD. We can facilitate this by providing a pre-built Phar for any commit (rather than forcing people to build from source).
For any commit that runs on Travis CI (master or PRs), upload a phar to transfer.sh. We can grab a link to this phar from the Travis CI logs and distribute to anyone for testing. The link is good for 14 days.
1. Check the Travis CI logs on this PR and ensure you can download the ACLI dev build (I'll add a link here):
- https://travis-ci.com/github/acquia/cli/jobs/497913802#L502 (click to expand)
- https://transfer.sh/4wc5M/acli.phar
=> Upload acli.phar on every commit

src/Helpers/LocalMachineHelper.php
**Motivation**
Fixes #495
On Windows, assume `start` exists instead of checking for it (AFAICT, it _always_ exists as a built-in in common shells, and there's not a consistent way of finding commands across shells on Windows).
Also improve error output to guide people towards self-solving the issue.
Fix `commandExists` to properly find commands on Windows. Good luck with that one, I couldn't untangle how to check that `start` exists, and any solution would probably be shell-specific.
3. Run …
=> Fix #495: [windows] No browser found

composer.json, composer.lock, src/Command/Pull/PullCommandBase.php, src/Command/Push/PushArtifactCommand.php, src/Command/Push/PushCodeCommand.php, symfony-fs-mirror.patch, tests/phpunit/src/Commands/Pull/PullCodeCommandTest.php, tests/phpunit/src/Commands/Pull/PullCommandTestBase.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php, tests/phpunit/src/Commands/Push/PushCodeCommandTest.php
**Motivation**
Currently, ACLI supports pulling code but not pushing it. Additionally, it has no awareness of the distinction between "source" and "build" repositories. Best practice for Drupal 8+ using Composer is to keep a "source" repo (without dependencies committed, i.e. Github) and an "artifact" repo (with dependencies committed, i.e. Acquia Git). The only way to support this workflow today is with `blt deploy`, which is overly complicated for most users.
Replicate the `blt deploy` command in ACLI, but in a much more streamlined form that's more tightly coupled with Acquia environments, so it's a true deployment manager (not just an artifact builder): allow users to select a specific environment to push to (as long as that environment has a branch checked out). …
=> [push:code] build artifacts

src/Command/Pull/PullCommandBase.php
**Motivation**
Fixes #509
Re-index the environments array after unsetting the prod environment, in case it's ordered like:
- dev
- prod
- stage
3. Run `acli push:files` on an environment previously affected by this issue, and select the non-default environment.
Unfortunately this isn't easy to write an automated test for, because we don't mock a multi-environment response _anywhere_ in our test suite (due to a CXAPI bug). I opened an internal ticket to fix this.
=> Fix #509: [push/pull] cannot select environment

src/Command/CommandBase.php, src/Command/Pull/PullCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, src/Command/Pull/PullFilesCommand.php, src/Command/Push/PushDatabaseCommand.php, src/Command/Push/PushFilesCommand.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
**Motivation**
Fixes #483
Add `site` argument to `push:files`, `push:db`, `pull:files`, and `pull:db`.
3. Test the affected `push/pull` commands, including multisite arguments as well as the `default` site argument (since `default` is handled a little differently between commands)
=> Fix #483: [pull/push] add site argument

src/Command/Pull/PullCommandBase.php, src/Helpers/LocalMachineHelper.php, tests/phpunit/src/Commands/Pull/PullCodeCommandTest.php
**Motivation**
Fixes #535
Use the safer `execute()` method and pass environment variables as context, rather than as part of the CLI.
3. Run `acli pull:code` on Windows (Git Bash or Powershell) and confirm it works.
This has been broken for almost a year 😱 : https://github.com/acquia/cli/pull/156
This regression occurred because we mock Git shell commands, we don't actually try to execute them in a Windows environment. I'm not sure how we could catch this without end-to-end integrated tests (e.g. …
=> Fix #535: [pull:code][windows] GIT_SSH_COMMAND not recognized

src/Command/CommandBase.php, src/Command/Pull/PullCommandBase.php
**Motivation**
Fixes DX-3908
If users fail to configure sites.php for an environment and pull a db or files from a multisite install, they will be pretty confused when Drupal loads the default site instead of whatever multisite they selected.
Note that this isn't ACLI misbehaving, it always pulls the db or files as expected. The problem is that Drupal may not know to utilize the db/files that were just pulled, causing a split-brain scenario where it tries to load files from the wrong site directory.
Warn users of the need to configure sites.php
=> Warn users to configure sites.php

config/prod/services.yml, src/CloudApi/AccessTokenConnector.php, src/CloudApi/CloudCredentials.php, src/CloudApi/ConnectorFactory.php, tests/phpunit/src/CloudApi/AccessTokenConnectorTest.php
**Motivation**
Ensure that expired access tokens are not used.
Use ACLI_ACCESS_TOKEN_EXPIRY to check if ACLI_ACCESS_TOKEN is expired. If it is expired, the typical authentication flow will occur, checking cloud_api.conf.
3. Get a real access token. It will expire after 5 minutes
* Open Google Chrome Dev Tools
* Change to "network" tab to begin recording requests
* Login to Acquia Cloud
* Immediately, before changing URLs, filter the network tab for the "token" resource and select it
* Select the …
=> Check access token expiration.

src/Command/CommandBase.php, src/Command/HelloWorldCommand.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/UpdateCommandTest.php
**Motivation**
Fixes the following error:
```
acli self-update
Warning: file_get_contents(https://api.github.com/repos/acquia/cli/releases): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
in phar:///opt/local/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php on line 70
Warning: file_get_contents(https://api.github.com/repos/acquia/cli/releases): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
in phar:///opt/local/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php on line 70
In SelfUpdateCommand.php line 74:
API error - no release found at GitHub repository acquia/cli
```
Do not throw an exception when an update check fails. Instead, return FALSE (as if there is no update) and log …
=> Do not throw exception when update check fails.

src/Command/CommandBase.php, src/EventListener/ExceptionListener.php
**Motivation**
```
acli pull:db [] -vvv
Box Requirements Checker
========================
> Using PHP 7.4.15
> PHP is using the following php.ini file:
/usr/local/php7.4/etc/cli/php.ini
> Checking Box requirements:
✔ The application requires the version "^7.3 | ^8.0" or greater.
✔ The application requires the extension "json".
✔ The package "brick/math" requires the extension "json".
✔ The package "guzzlehttp/guzzle" requires the extension "json".
✔ The package "ramsey/uuid" requires the extension "json".
✔ The package "zumba/amplitude-php" requires the extension "curl".
[OK] Your system is ready to run the application.
Acquia CLI version: 1.12.0
Warning: file_get_contents(https://api.github.com/repos/acquia/cli/releases): failed to open stream: HTTP request failed! HTTP/1.1 403 rate …
```
=> Avoid GitHub rate limiting.

src/Command/NewCommand.php
**Motivation**
Fixes #NNN
3. Login to IDE.
4. Run `acli new`
5. Validate that /home/ide/project is default dir.
=> Default dir to /home/ide/project in IDE for new command.

src/Command/Api/ApiCommandBase.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes #542
For api:* commands, print request info at debug verbosity level.
3. `./bin/acli api:applications:find -vvv`
4. Validate output contains curl debug output. E.g.,
```
./bin/acli api:applications:task-list [uuid] --limit=2 --offset=1 -vvv
Acquia CLI version: @package_version@
*   Trying 104.19.229.55:443...
* TCP_NODELAY set
* Connected to cloud.acquia.com (104.19.229.55) port 443 (#0)
[...lots more...]
* Connection #0 to host cloud.acquia.com left intact
```
**Merge …
=> Fixes #542: provide the HTTP request in debug-level output.

src/Command/CommandBase.php
**Motivation**
Fixes #609 
Check that $input is set before accessing it.
I feel like we should do more to stop this kind of thing from happening again, but I'm not sure what.
- Calling the command class from within an exception listener feels dirty. I'd prefer to move update functionality into a separate helper, but it would add a lot of complexity.
- We already catch some types of exceptions during update checks, could we check more? Just adding a catch for null pointer wouldn't necessarily prevent the next bug, we should probably catch everything or nothing.
2. Clear …
=> Fix #609: Uncaught error during update check

.travis.yml
Github nags me every time we use this deploy key: https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/
This can't be tested prior to merging, but I followed the same process for BLT Launcher and you can see that it worked: https://github.com/acquia/blt-launcher/releases/tag/v1.0.3
Let's do a minor release after https://github.com/acquia/cli/pull/603 is merged to test this.
=> Update deploy token

src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
**Motivation**
Fixes #596
Add `--download` option that skips scripts and the db import.
Add a separate command, or have people use `api:environments:database-backup-download`
3. Run `pull:db` to verify that the MySQL import still works as before.
4. Run `pull:db --download` to verify that the MySQL import and scripts are skipped, and the file location is echoed.
=> [pull:db] --no-import option

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Archive/ArchiveExporterCommandTest.php, tests/phpunit/src/Commands/Pull/PullCommandTestBase.php, tests/phpunit/src/Commands/Push/PushDatabaseCommandTest.php
**Motivation**
Fixes #621.
Skip progress if pv is not installed, show warning.
Throw fatal error if pv is not installed.
2. Ensure `pv` does not exist, `which pv`. 
2. Execute `acli db:push`
3. Validate that warning "Please install `pv` to see progress bar'" appears and that DB pull completes successfully.
=> Fixes #621: Skip progress if pv is not installed, show warning.

src/Command/Pull/PullCommandBase.php
**Motivation**
```
acli pull --no-code --no-files
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Acquia\Cli\Command\Pull\PullCommandBase::pullDatabase(), 2 passed in phar:///usr/local/bin/acli/src/Command/Pull/PullCommand.php on line 59 and exactly 4 expected in phar:///usr/local/bin/acli/src/Command/Pull/PullCommandBase.php:112
Stack trace:
#0 phar:///usr/local/bin/acli/src/Command/Pull/PullCommand.php(59): Acquia\Cli\Command\Pull\PullCommandBase->pullDatabase(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///usr/local/bin/acli/vendor/symfony/console/Command/Command.php(299): Acquia\Cli\Command\Pull\PullCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), …
```
=> Pull command fails due to missing variable default values

bin/acli, config/prod/services.yml, src/Command/Api/ApiCommandHelper.php, src/Command/CommandBase.php, src/EventListener/ComposerScriptsListener.php, src/EventListener/ExceptionListener.php, src/EventListener/TerminateListener.php, src/Helpers/LocalMachineHelper.php, src/Helpers/SshHelper.php, tests/fixtures/project/composer.json, tests/phpunit/src/Application/ExceptionApplicationTest.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php, tests/phpunit/src/Commands/Api/ApiListCommandTest.php, tests/phpunit/src/Commands/Ide/IdeXdebugToggleCommandTest.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php, tests/phpunit/src/Commands/Remote/DrushCommandTest.php, tests/phpunit/src/Commands/Remote/SshCommandTest.php, tests/phpunit/src/Commands/Remote/SshCommandTestBase.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes #641
After any ACLI command is run, ACLI will check `$(pwd)/composer.json` for a `post-acli-($command name)` script and execute it if present. E.g., `post-acli-db:pull`.
3. `cd` into a Drupal application directory containing a composer.json.
4. Add an entry to the `scripts` key in the composer.json:
```
"post-acli-ide-list": [
"echo \"Hello world\""
]
```
5. Run `[path to acli]/bin/acli ide-list -vvv`
6. Observe:
```
Executing composer script `post-acli-ide-list` defined …
```
=> Fixes #641: Trigger custom scripts after acli pull commands

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/InferApplicationTest.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
**Motivation**
Fixes #599 
When a user selects an ACSF site database, save that choice and re-use it for the files prompt.
=> Fixes #599: Autoselect db and files if site is selected.

.github/workflows/ci.yml
**Motivation**
Our last release failed because the Action did not have sufficient permissions to create a release: https://github.com/acquia/cli/runs/3634954570?check_suite_focus=true
This was missed in testing. I did verify that Actions releases worked on my fork, but didn't realize that Actions as a whole had entirely different permissions between my personal and Acquia orgs. I've since fixed that.
Add necessary permissions.
See that the release succeeds on my fork, now that permissions are synced between the orgs: https://github.com/danepowell/cli/releases/tag/actions5
=> Automated release failures

src/Command/Push/PushArtifactCommand.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php
**Motivation**
Allow `push:artifact` to be used non-interactively by adding options for dest-git-url and dest-git-branch.
* Add new options to `push:artifact` command
- `acli push:artifact --source-git-url=[something] --dest-git-url=[something] --git-branch=[something]`
=> Allow git url and branch to be passed to push:artifact.

src/Command/Pull/PullCommandBase.php, src/Command/Push/PushArtifactCommand.php, tests/phpunit/src/Commands/Pull/PullCommandTestBase.php
**Motivation**
Sometimes the `docroot/core` directory does not exist in the source because `composer install` was not run, and this is ok.
Check for only `docroot`.
=> Do not check source dir for core dir.

CONTRIBUTING.md, composer.json, composer.lock
**Motivation**
Upstream PR was merged: https://github.com/consolidation/self-update/pull/5
Stop using our own fork of consolidation/self-update
We have to keep it aliased to 1.1 because of a conflict with https://github.com/typhonius/acquia-logstream
3. Follow the steps to [test the update command](https://github.com/acquia/cli/blob/master/CONTRIBUTING.md#testing-the-update-command)
=> Unfork consolidation/self-update

src/Command/Push/PushArtifactCommand.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php
**Motivation**
Force add `docroot/autoload.php`.
Force add `docroot/autoload.php`.
Figure out why some codebases have a `docroot/.gitignore` with a line entry for `autoload.php`.
3. Run `push:artifact -vvv`.
4. Validate that `git add -f docroot/autoload.php` appears in the output.
=> Fixes #676: Force commit docroot/autoload.php with push:artifact.

src/Command/Ide/IdeCreateCommand.php, src/Command/Ide/IdeListCommand.php, src/Command/Ide/IdeListMineCommand.php, tests/phpunit/src/Commands/Ide/IdeListCommandMineTest.php
**Motivation**
Fixes #711
* Add a new `ide:list-mine` command.
* Rename `ide:list`	 to `ide:list-app`, leave an `ide:list` for backwards compatibility. 
Change behavior of `ide:list` to make application argument optional.
3. Run `ide:list-app`
4. Run `ide:list-mine`
=> Fixes #711: Adding ide:list-mine command.

src/Command/Ssh/SshKeyDeleteCommand.php, tests/phpunit/src/Commands/Ssh/SshKeyDeleteCommandTest.php
**Motivation**
Fixes #NNN
3. run `acli ssh-key:create-upload` to create a test key
4. run `acli ssh-key:delete` to delete the key
=> Delete corresponding local key when Cloud key is deleted.

src/Command/Pull/PullCommandBase.php, src/Helpers/LocalMachineHelper.php, src/Helpers/SshHelper.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Pull/PullFilesCommandTest.php
**Motivation**
If the files directory doesn't exist, the shell commands don't exit cleanly and the whole process fails.
- Ensure files directory exists before trying to read it
- Capture and rethrow any process errors
3. Delete files directory locally, or create a brand new IDE (which will be missing the files directory) and run `acli pull`.
=> CLI-520: [pull:files] not enough free disk space

src/Command/Api/ApiCommandHelper.php
Enable `api:ide:delete`. It is the only method of deleting an IDE via the command line using only the IDE uuid. `ide:delete` by comparison requires knowing the application UUID.
**Motivation**
There is currently no way to delete an IDE via IDE uuid.
Enable `api:ide:delete`.
None.
3. Run `acli api:ide:delete --help`
=> CLI-532: Enable api:ide:delete

composer.json, composer.lock, src/Command/Push/PushArtifactCommand.php, src/DataStore/YamlStore.php, symfony.lock, tests/fixtures/.acquia-cli.yml, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php
Add options to `acli push:artifact`:
* --destination-git-urls, an array of git urls to push to
* --destination-git-branch, the git branch to push to.
Allow same options to be defined in .acquia-cli.yml:
```
push:
artifact:
destination-git-url:
- https://github.com/example/cli.git
- https://github.com/example2/cli.git
destination-git-branch: master
```
=> Make `push:artifact` push to multiple git repos

src/Command/CommandBase.php, src/Command/Ide/IdeOpenCommand.php, src/EventListener/ExceptionListener.php, tests/phpunit/src/Application/ExceptionApplicationTest.php
**Motivation**
Fixes #722
Throw an exception any time a command requires a linked application, but no application is provided or found.
3. Find a Drupal site that's _not_ linked to a Cloud app
4. Run a command requiring a linked application non-interactively, i.e. `acli remote:aliases:download -n -vvv`
5. Expect a clear exception rather than a bunch of PHP errors.
=> Fix #722: Errors linking Cloud application when running non-interactively

src/Command/NewCommand.php, tests/phpunit/src/Commands/NewCommandTest.php
**Motivation**
`acli new` is failing because it tries to install Drupal 9.3, but ACMS includes a patch that fails to apply to Drupal 9.3
Stop running `composer update` so that we get the known-good dependencies provided by the project templates. As soon as ACMS (and all other packages) are compatible with Drupal 9.3, the templates will update their dependencies to match.
As a happy side effect, this should make `acli new` an order of magnitude faster.
3. Run `acli new`, verify that you get Drupal 9.2 + ACMS with the …
=> Fix acli new failing due to ACMS patch

src/Command/CommandBase.php
**Motivation**
Fixes #731
Fixes the canonical sites directory in ACN applications. Seems like ACN changed this recently.
This is an alternative to #739 
3. Run `acli pull:files` against an ACN app.
I'm unable to test this at a moment as I try to set up a multisite ACN app. But if everyone's happy with the approach I'll do further testing and fix tests.
=> Fix #731: Incorrect sites/files directory on ACN

src/Command/CommandBase.php, src/Command/Pull/PullCommandBase.php, src/Command/Push/PushFilesCommand.php, src/Helpers/TelemetryHelper.php, tests/phpunit/src/Commands/Pull/PullFilesCommandTest.php, tests/phpunit/src/Commands/Push/PushFilesCommandTest.php, tests/phpunit/src/Commands/Remote/AliasesDownloadCommandTest.php
**Motivation**
Fixes #731
Add the -z option to rsync to compress the files prior to transfer.
3. `acli pull:files`
=> Fixes #731: Compress files for push:files and pull:files commands

src/Command/Remote/AliasesDownloadCommand.php, tests/phpunit/src/Commands/Remote/AliasesDownloadCommandTest.php
**Motivation**
Fixes #721
Add --destination-dir option to remote:aliases:download. 
3. `acli remote:aliases:download --destination-dir=mytestdir`
=> Fixes #721: Add --destination-dir option to remote:aliases:download.

src/Command/Ssh/SshKeyCreateCommand.php
**Motivation**
Fixes #611
The `ssh-key:create` command will fail with an informative error if both `--password` is not used and a non-interactive shell is used.
=> Fixes #611: When the --no-interaction flag is passed, fail informatively.

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullCommandTestBase.php
**Motivation**
Removes an errant `}` from display output in pull commands. This was caused by an output callback emitting output when no checklist item was active, causing the artifact to never be cleared.
Don't use an output callback when checking for a db connection in the pull commands.
Add a checklist item before the check for a db connection.
3. Run `pull:db`.
=> Remove display artifact from pull commands.

src/Command/Push/PushArtifactCommand.php
**Motivation**
Enable CI/CD jobs to more easily use `artifact:push` command by setting options via environmental variables.
Add ACLI_PUSH_ARTIFACT_COMMIT_MSG, ACLI_PUSH_ARTIFACT_DESTINATION_GIT_BRANCH, AND ACLI_PUSH_ARTIFACT_DESTINATION_GIT_URLS env var support.
=> Allow push:artifact args to be passed via env var.

src/Command/Api/ApiCommandBase.php, src/Command/CommandBase.php, src/EventListener/ExceptionListener.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php
**Motivation**
Fixes #757: Support binary data arguments for Cloud API.
Send binary data as multipart form data via Guzzle.
3. ` ./bin/acli api:applications:search:configuration-set-create eemgrasmick [zip file path]`
=> Fixes #757: Support binary data arguments for Cloud API.

.github/workflows/ci.yml, composer.json, composer.lock, tests/phpunit/src/Commands/Ide/IdePhpVersionCommandTest.php, tests/phpunit/src/Misc/LandoInfoTrait.php
**Motivation**
PHP 7.3 was recently EOL'ed https://www.php.net/supported-versions.php
Support PHP 7.4+ only.
N/A
Confirm ACLI works well both with PHP 7.4 and 8.0, especially with CI.
=> CLI-604: Drop support for PHP 7.3

src/Command/Push/PushArtifactCommand.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php
**Motivation**
Fixes #774: acli push:artifact does not force add scaffold files.
Correctly define the web root.
=> Fixes #774: acli push:artifact does not force add scaffold files.

src/Command/NewCommand.php, tests/phpunit/src/Commands/NewCommandTest.php
**Motivation**
As of Composer 2.2, running `acli new` will ask to grant permissions to plugins. 
Run `composer create-project` with a `--no-interaction` flag.
3. Run `acli new`
4. Validate that there are no prompts to allow plugins.
=> Remove plugin prompts from `acli new` command. (#784)

src/Command/CodeStudio/CodeStudioWizardCommand.php
**Motivation**
Cloud IDE has the GITLAB_HOST set to an absolute URL rather than a host name. This breaks `cs:wizard`.
Parse the hostname from the URL.
Fix the variable in Cloud IDE.
=> Parse GitLab hostname from url.

src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
**Motivation**
This enables code studio to set ACQUIA_JOBS_DEPRECATED_UPDATE and ACQUIA_JOBS_COMPOSER_UPDATE to "false."
Each pipeline gets these variables set to true for the pipeline.
=> CLI-632: Add variables to scheduled jobs.

src/Command/App/AppOpenCommand.php, src/Command/CommandBase.php, src/Command/OpenCommand.php, src/Helpers/LocalMachineHelper.php, tests/phpunit/src/Commands/App/AppOpenCommandTest.php
**Motivation**
Enable users to easily open a Cloud application in Cloud UI via `app:open` command.
Add `app:open` command.
3. `cd` into a Drupal project directory.
4. Run `acli app:open`
=> CLI-662: Add open:app command.

src/Command/CodeStudio/CodeStudioWizardCommand.php
**Motivation**
Cloud applications with special characters in the name will cause a failure in cs:wizard.
Strip non alpha numeric characters from project names.
=> Transform project name into asciii safe slugs.

src/Command/Remote/AliasesDownloadCommand.php, tests/fixtures/project/testdir/sites/devcloud2.site.yml, tests/phpunit/src/Commands/Remote/AliasesDownloadCommandTest.php
**Motivation**
Fixes #790: add --all option to remote:aliases:download.
Add --all option to remote:aliases:download.
3. Run `acli remote:aliases:download --all`
4. Validate all aliases were downloaded to drush/sites.
5. Run `acli remote:aliases:download`
6. Validate only one alias file was created in drush/sites.
=> Fixes #790: add --all option to remote:aliases:download (CLI-629)

.gitignore, composer.json, composer.lock, src/Command/CodeStudio/CodeStudioWizardCommand.php, src/Command/Email/EmailInfoForSubscriptionCommand.php, symfony.lock, tests/phpunit/src/Commands/Email/EmailInfoForSubscriptionCommandTest.php
**Motivation**
Supplements bulk Platform Email functionality/support by showing users the verification statuses of email domains registered to a subscription, as well as associated (or dissociated) domains for each application of the subscription.
Add a new `email:info` command
3. `./bin/acli email:info`
4. Verify that CSV files are successfully written to a folder called "domain-info-*" in the directory where `email:info` is being run.
=> CLI-685: Set up email:info command

src/Command/Email/EmailInfoForSubscriptionCommand.php
**Motivation**
Ensures that formatting of the name of the created CSV file directory is clear when running `email:info`.
**Before**
**After**
=> Hotfix: Adjust formatting of CSV file autogeneration message in email:info command

.github/workflows/jira.yml
@grasmash you can see this working for BLT:
- https://github.com/acquia/blt/issues/4488
- https://github.com/acquia/blt/blob/main/.github/workflows/jira.yml
I'm going to port it to our other open-source projects as well.
This can't really be tested before merging. After it's merged I'll create a test issue.
=> Automatically create Jira tickets

src/Command/CommandBase.php, src/Command/Ide/IdeDeleteCommand.php, src/Command/Ide/Wizard/IdeWizardCommandBase.php, src/Command/Ide/Wizard/IdeWizardDeleteSshKeyCommand.php, src/Command/Ssh/SshKeyCommandBase.php, src/Command/Ssh/SshKeyDeleteCommand.php, src/Helpers/SshCommandTrait.php, tests/phpunit/src/Commands/Ide/IdeDeleteCommandTest.php, tests/phpunit/src/Commands/Ide/Wizard/IdeWizardDeleteSshKeyCommandTest.php
**Motivation**
I cannot run tests to completion locally, because some commands redispatch to SshKeyDeleteCommand via CommandBase::executeAcliCommand(). This does not preserve the command tester input, so confirmation dialogs in SshKeyDeleteCommand hang awaiting input.
If there's one lesson I've learned from BLT and Drush, it's that redispatching is the root of all evil. 👿 
Instead of redispatching, move the SSH-key deletion business logic to a shared SshCommandTrait. I want to eventually convert all of our "base" commands (SshCommandBase, IdeCommandBase, etc) into traits, so they can be mixed-and-matched. For instance, by using traits instead of an inherited command base, the IdeWizardCreateSshKeyCommand can now be _both_ an SSH command and an IDE command. …
=> CLI-575: Fix stalled tests

src/Command/Remote/AliasesDownloadCommand.php
=> Fixes #864: Fatal error with remote:aliases:download in ACLI 1.25.

src/Command/CommandBase.php, src/Command/Push/PushArtifactCommand.php, src/Command/Ssh/SshKeyCommandBase.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php
**Motivation**
Fixes #854: Add --tag option to push:artifact.
Add a `--tag-name=[tag]` option that will create and push a git tag rather than a branch.
3. `cd` into a drupal application directory
4. `../cli/bin/acli push:artifact --destination-git-branch=[branch] --tag-name=[tag] -v`
=> Fixes #854: Add --tag option to push:artifact.

.github/workflows/ci.yml, .gitignore, composer.json, composer.lock, src/Command/Email/ConfigurePlatformEmailCommand.php, symfony.lock, tests/phpunit/src/Commands/Email/ConfigurePlatformEmailCommandTest.php
**Motivation**
Fixes #834 
Adds the option of a Zone File output format when asked to export DNS records after registering a domain in the `email:configure` script
3. `./bin/acli email:configure` - when asked to choose a file type for exporting DNS records, choose 'Zone File' and verify contents of `dns-records.zone` in the root of the directory where the command was run
=> CLI-677: Fixes #834: For email:configure, add zone file as output format

.gitignore, composer.json, composer.lock, src/Command/Email/ConfigurePlatformEmailCommand.php, symfony.lock, tests/phpunit/src/Commands/Email/ConfigurePlatformEmailCommandTest.php
**Motivation**
Re-implements #883, and in turn, #834
Re-implements Zone File output option when exporting DNS records in the `email:configure` wizard, but using a library that does not include a blocking PHP extension
3. `./bin/acli email:configure` - when asked to choose a file type for exporting DNS records, choose 'Zone File' and verify contents of dns-records.zone in the root of the directory where the command was run
=>  For email:configure, add zone file as output format (without GMP extension).

src/Command/App/LogTailCommand.php, src/Command/CommandBase.php, tests/phpunit/src/Commands/App/LogTailCommandTest.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes #875
It turns out other logs (mysql slow query, for instance) were borked as well, and some (balancer request) were missing entirely.
Depends on https://github.com/typhonius/acquia-logstream/pull/144
Use the available types provided by typhonius/acquia-logstream.
This drastically speeds up the command (by cutting out an API call) and makes it more reliable (since it turns out the API was lying to us 😄 )
https://github.com/typhonius/acquia-logstream/issues/143
3. `acli …
=> CLI-713: Fixes #875: Apache access logstream failing

composer.json, composer.lock, symfony.lock
**Motivation**
`composer install` using PHP 8 throws a bunch of errors from grumphp
Update grumphp to use https://github.com/phpro/grumphp/pull/994
2. Use PHP 8
4. `rm -rf vendor && composer install`
5. Observe no more errors
=> CLI-688: Fix grumphp PHP 8 compatibility

composer.json
Note: branch is pinned to 139, because the generator is broken in 2.140
**Motivation**
Fixes #NNN
Adds a script that regenerates the openAPI spec for ACSF REST API, based on whatever resources are present in gardener repo.
run
```
composer  update-acsf-api-spec
```
... verify it has placed a new valid spec file in assets/acsf-spec.yaml
=> DG-25844. Add ACSF openAPI regen script.  

composer.json, composer.lock
**Motivation**
Fixes #912
Update phpstan
1. Check PHP 8.1 tests in CI and see that phpstan tests still run and don't generate warnings.
=> CLI-744: Fix #912: phpstan throws errors in PHP 8.1

.github/workflows/automerge.yml
**Motivation**
Violinist opens a lot of PRs for dependency updates. These are important, but mildly annoying to merge manually.
Merge them automatically as long as tests pass.
This can't be tested before merging and waiting for a Violinist PR, but you can see that the same script is working here: https://github.com/acquia/drupal-recommended-project/pull/111
=> Auto-merge Violinist PRs

src/Command/Pull/PullCommandBase.php
**Motivation**
`acli pull:database` takes an optional `site` parameter that is supposed to select the named Cloud database that you want to pull from. However, I found this was not working for some databases I tried to pull, and it instead prompted me to select a database.
array_search() could return 0 if the matching result is the first array item, or FALSE if there was no match. Hence, we need to do a non-identical comparison.
`acli pull:database sitename.env dbname1`
Expected behavior: `acli` will proceed to pull from the Cloud database named `dbname1`.
Actual behavior: If dbname1 happens to be the first item in the response from `/environments/UUID/databases`, you'll be prompted:
```
Choose a database [sitename (default)]:
[0] dbname1
[1] dbname2 …
```
=> Allow for 0-index when determining cloud database name

.github/release-drafter.yml, .github/workflows/release-drafter.yml
See https://github.com/acquia/cli/runs/6210108729?check_suite_focus=true
```
Run release-drafter/release-drafter@v5
with:
config-name: release-drafter.yml
env:
GITHUB_TOKEN: ***
"pull_request_target.opened" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
"pull_request_target.reopened" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
"pull_request_target.synchronize" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
"pull_request_target.edited" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
acquia/cli: Found 6[2](https://github.com/acquia/cli/runs/6210108729?check_suite_focus=true#step:2:2) releases
{ name: 'event', id: …
```
=> Autolabel pull requests from Violinist

src/CloudApi/CloudCredentials.php
This code can never be executed because the datastore will throw an exception if it encounters an invalid config, and the legacy config is not considered valid
=> Remove legacy cloud key code

composer.lock, symfony.lock
This package is abandoned and generates warnings on `composer install`. I removed it in https://github.com/typhonius/acquia-php-sdk-v2/pull/237, we just need to update our dependency on acquia-php-sdk-v2 to remove it completely.
=> Remove webmozart/path-util

.github/workflows/ci.yml, .github/workflows/mutation.yml, composer.json
It's twice as fast! Compare 2 m ([last run with Xdebug](https://github.com/acquia/cli/runs/6233376495?check_suite_focus=true)) to 1 m ([this run with pcov](https://github.com/danepowell/cli/runs/6235229772?check_suite_focus=true))
=> Use pcov instead of xdebug for coverage

src/AcsfApi/AcsfClientService.php, tests/phpunit/src/AcsfApi/AcsfServiceTest.php
Just trying my hand at this... finding mutants turns out to be a lot easier than killing them 😄 
To verify this is helping:
- Observe escaped mutants like this one in prior test runs: https://github.com/acquia/cli/runs/6231672360?check_suite_focus=true#step:6:85
- Observe that this mutant no longer exists on this PR: https://github.com/acquia/cli/runs/6233376232?check_suite_focus=true#step:6:34
You can also run mutation tests locally and compare before and after: `composer infection-install && ./build/infection.phar --filter=AcsfClientService.php -j2 --only-covered`
=> Kill escaped mutants

.github/workflows/mutation.yml
Nowhere is it documented how many threads are available on GitHub Actions runners, but experimentation shows 8 threads to be fastest. We also need to inject INFECTION_DASHBOARD_API_KEY to get that sweet sweet badge working.
=> Fix Stryker reporting

.github/workflows/mutation.yml
- Mutation reporting was broken when we added Stryker integration, this fixes it
- This also reduces the verbosity of PR reporting by [only mutating changed _lines_](https://infection.github.io/guide/command-line-options.html#git-diff-lines) instead of changed _files_. This especially helps when working on big files like CommandBase.php, which can generate hundreds of mutations.
=> Fix mutation reporting, make it less verbose

.github/workflows/release-drafter.yml
`pull_request` and `pull_request_target` triggers are essentially identical and using both in the same workflow results in multiple workflows running at once.
The only difference is that `pull_request_target` runs in the context of the base branch and injects repo secrets. Using `pull_request` is safer and just requires tweaking permissions.
=> Remove duplicate release drafter trigger

.github/workflows/mutation.yml, src/Command/CommandBase.php, src/Command/Ide/Wizard/IdeWizardCommandBase.php, src/Command/Ide/Wizard/IdeWizardCreateSshKeyCommand.php, src/Command/Push/PushArtifactCommand.php, src/Command/Ssh/SshKeyCommandBase.php, src/Helpers/SshHelper.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Ide/Wizard/IdeWizardCreateSshKeyCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyUploadCommandTest.php, tests/phpunit/src/Commands/WizardTestBase.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes #818 
- Add permission checks for git, prod, and non-prod environments (the three places where SSH keys can be installed)
- Warn the user if they lack permissions for any of these
- Poll all three places to make sure SSH keys are fully installed and available
0. Use or mimic an IDE (export REMOTEIDE_UUID and AH_SITE_ENVIRONMENT=ide)
3. Remove any existing local IDE SSH keys
4. Run `acli ide:wizard`
5. Depending on whether you have permissions to access git / prod / non-prod environments in the …
=> CLI-657: Improve SSH key polling and permission checks

composer.json, composer.lock, src/Command/Api/ApiCommandHelper.php
=> Fixes #969: acli update should only download when a new release is available

src/Command/Ide/IdeCreateCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Ssh/SshKeyCommandBase.php, tests/phpunit/src/ApplicationTestBase.php, tests/phpunit/src/TestBase.php
**Motivation**
Tests are slower than necessary. This reduces the duration of unit tests from 90 seconds to 20 seconds!
- Stop clearing the kernel cache between runs
- Run the event loop once immediately when it's created before starting the periodic loop. This feels a little hacky but I don't know how else to fix it.
=> CLI-754: Fix slow PHPUnit tests

.gitignore
Now that we mirror test fixtures to a unique directory for every test, we no longer need to ignore files in the origin fixture directory (nothing should ever be created there). In fact, we want Git to alert us to any cruft in the fixture directory since it can cause bad behavior (I wasted a couple hours due to this yesterday, some rogue file was causing tests to behave differently locally than in CI).
=> Remove fixtures from gitignore

src/Command/App/NewCommand.php, src/Command/App/UnlinkCommand.php, src/Command/Self/ClearCacheCommand.php, src/Command/Self/ListCommand.php, src/Command/Self/TelemetryCommand.php, src/Command/Self/TelemetryDisableCommand.php, src/Command/Self/TelemetryEnableCommand.php, tests/phpunit/src/Commands/Acsf/AcsfListCommandTest.php, tests/phpunit/src/Commands/Api/ApiListCommandTest.php, tests/phpunit/src/Commands/ClearCacheCommandTest.php, tests/phpunit/src/Commands/NewCommandTest.php, tests/phpunit/src/Commands/TelemetryCommandTest.php, tests/phpunit/src/Commands/TelemetryDisableCommandTest.php, tests/phpunit/src/Commands/TelemetryEnableCommandTest.php, tests/phpunit/src/Commands/UnlinkCommandTest.php, tests/phpunit/src/Misc/EnvDbCredsTest.php, tests/phpunit/src/Misc/LandoInfoTest.php, tests/phpunit/src/TestBase.php
This moves commands to the following new locations:
- `app:new`
- `app:link`
- `app:unlink`
- `self:list`
- `self:telemetry:toggle`
- `self:telemetry:disable`
- `self:telemetry:enable`
It also adds aliases to preserve the original command.
Annoyingly, Symfony has marked the DumpCompletion command (`completion`) as final so we can't extend it to change the name: https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Console/Command/DumpCompletionCommand.php
We could open a PR with Symfony to change this but I'm not sure it's worth the effort.
=> CLI-679: Consolidate internal commands under self

src/Command/Api/ApiBaseCommand.php
3. `./bin/acli acsf:users:delete`
4.  Enter `80` as user id.
=> Fixes CLI-768: CLI string input with only digits should be interpretted as integer.

src/Command/Acsf/AcsfApiBaseCommand.php, src/Command/Api/ApiBaseCommand.php, tests/phpunit/src/Commands/Acsf/AcsfApiCommandTest.php
**Motivation**
Fixes CLI-779: Support multiple data types in arguments.
3. `./bin/acli acsf:groups:make-members-admins`
=> Fixes CLI-779: Support multiple data types in arguments.

src/AcsfApi/AcsfClient.php, src/AcsfApi/AcsfClientService.php, src/AcsfApi/AcsfCredentials.php, src/Command/Acsf/AcsfApiAuthLoginCommand.php, src/Config/CloudDataConfig.php, tests/phpunit/src/AcsfApi/AcsfServiceTest.php, tests/phpunit/src/AcsfApi/EnvVarAcsfAuthenticationTest.php, tests/phpunit/src/Commands/Acsf/AcsfAuthLoginCommandTest.php, tests/phpunit/src/Commands/Acsf/AcsfCommandTestBase.php
=> Fixes CLI-773: Change "password" to "key" for ACSF commands.

src/Command/CodeStudio/CodeStudioCommandTrait.php, src/Command/CodeStudio/CodeStudioPipelinesMigrateCommand.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioPipelinesMigrateCommandTest.php
This PR consist following fixes:
1. Added needs for build job, so that new "build drupal" job will be dependent on "'Build Code','Manage Secrets'" job.
2. At the end of the command it will remove the acquia-pipelines.yml file from the root repository.
3. "validateEnvironment" method was not getting called which is used to check GITLAB_HOST environment variable is set or not.so added it in "authenticateWithGitLab" method.
=> ACLI migrate command fix.

src/Command/Api/ApiBaseCommand.php
**Motivation**
Fixes issue that causes `acli api:environments:code-switch` to throw error `Cloud Actions are not enabled on this environment.`.
Previously, an option of type array would have a value of `[]` when unset. Now it will have a null value.
3. `./bin/acli api:environments:code-switch`
=> Set value of unset options to NULL.

.github/workflows/ci.yml, composer.json
Fixes #1043
I updated the branch protection settings to require the new `check` job, which will always run (even if a prior job fails).
Proof that GitHub now blocks merging on test failures:
=> Fix #1043: Branch protection failure

.editorconfig, phpcs.xml.dist, src/Command/Ide/IdeCommandBase.php, src/Command/Pull/PullCommandBase.php, src/Helpers/IdeCommandTrait.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Pull/PullCodeCommandTest.php
**Motivation**
#1075 did not work as intended because the `PHP_VERSION` env var is not set when invoking ACLI via a specific version of PHP (rather than via the PHP wrapper)
Revert functional changes in #1075 and instead read default PHP version from the version-selection config file.
Run `php --version` to discover the actual default PHP version, but then we're left with the challenge of parsing the version string which requires some ugly bash-fu.
1. Start an IDE (needs to have an active SSH agent, so probably in staging instead of local)
2. Apply changes to acli.sh from the IDE counterpart to this PR (to invoke ACLI via PHP 8)
3. Download the PR build of ACLI from transfer.sh and modify acli.sh to use it instead of the …
=> IDE-2333: Detect PHP version in IDE via config file

src/Command/CodeStudio/CodeStudioCommandTrait.php, src/Command/CommandBase.php, src/EventListener/ExceptionListener.php, tests/phpunit/src/Application/ExceptionApplicationTest.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php, tests/phpunit/src/Commands/ClearCacheCommandTest.php, tests/phpunit/src/Commands/Remote/SshCommandTestBase.php, tests/phpunit/src/TestBase.php
**Motivation**
We consider an application alias to be equivalent to an application name (nee "sitegroup"). The problem is that multiple realms can have identically-named applications, leading to undefined behavior for applications that exist across multiple realms. A fully-qualified application alias should include both the realm and name (together, the "hosting id").
Make the application equivalent to a "hosting id", which is a combination of application realm and name in the form `realm:name`. If realm is omitted but the alias is still unique (i.e. matching only one app), the alias will work as before and return that app. If the realm is omitted and multiple applications match, throw an exception.
Theoretically it is possible for multiple applications in the _same_ …
=> CLI-549: Allow for realm specificity

src/Command/Api/ApiCommandHelper.php
**Motivation**
It is sub-optimal to only link to Cloud Platform API docs when it comes to ACSF commands.
For ACSF commands, we should also link to https://dev.acquia.com/api-documentation/acquia-cloud-site-factory-api
Contextually return the docs whether it's an `acsf` command or not. Seems like a lot of overhead. Plus as a user you might _still_ want to read the regular API docs.
For example, run `acsf:themes:process-notifications`
=> CLI-821: ACSF api help points to incorrect documentation

src/Command/CommandBase.php, src/Helpers/AliasCache.php, tests/phpunit/src/Application/HelpApplicationTest.php, tests/phpunit/src/ApplicationTestBase.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php, tests/phpunit/src/Commands/Remote/SshCommandTestBase.php
**Motivation**
```
$ acli api:environments:ssl gardens-prod:c[snip]i.prod
In CacheItem.php line 159:
Cache key "gardens-prod:c[snip]i.prod" contains reserved characters "{}()/\@:".
api:environments:ssl-settings-find <environmentId>
```
Abstract cache to reduce code duplication so we don't overlook this again
3. Try using an environment alias with realm again. Note that `gardens` is not
=> CLI-825: Realm support for environment aliases

src/Command/App/TaskWaitCommand.php, src/Command/CommandBase.php, src/Command/Env/EnvCreateCommand.php, src/Command/Ide/IdeCreateCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Ssh/SshKeyCommandBase.php, src/Helpers/LoopHelper.php, tests/phpunit/src/Commands/ChecklistTest.php, tests/phpunit/src/Commands/Env/EnvCreateCommandTest.php, tests/phpunit/src/TestBase.php
**Motivation**
We (ab)use the react event loop in some ways that lead to unpredictable behavior and flaky tests. Specifically:
- Creating an event loop via `Factory::create()` is deprecated
- Creating an event loop at all (vs using the static singleton) is discouraged
- Explicitly running the event loop is discouraged
- Callbacks must not throw exceptions in event loops
- Timers added to loops must be explicitly cancelled. Simply stopping the loop isn't sufficient, as the timer will persist if the loop is restarted.
These are all [well-document bad behaviors](https://github.com/reactphp/event-loop).
Do things the right way. Abstract as much of the fiddly bits (cancelling timers and spinners) as possible into a single method so that we're not doing it a dozen different …
=> CLI-827: Deprecated usage of reactphp/event-loop

src/Command/CommandBase.php, src/Command/Ide/IdeCreateCommand.php, src/Helpers/LoopHelper.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/App/TaskWaitCommandTest.php
**Motivation**
`app:task-wait` only exits if progress reaches 100 but this won't happen if a task fails, which leads to a timeout.
Rename the 'success' callback to a 'done' callback, and make it the responsibility of that callback to determine success or failure. The LoopHelper shouldn't be involved in that.
And then of course change waitForNotificationToComplete to check for completion status ('completed' or 'failed').
3. Check a completed task, ensure it exits immediately as passing: `wacli app:task-wait …
=> CLI-815: app:task-wait does not track failed notifications

composer.json, composer.lock
**Motivation**
We had to use a HEAD release of grumphp to solve https://github.com/acquia/cli/pull/901 but that's not good practice long-term
Since there's a more recent stable release, go back to stable
=> grumphp back to stable release

composer.json, composer.lock, src/Command/Archive/ArchiveExportCommand.php, src/Command/Push/PushArtifactCommand.php, tests/phpunit/src/Commands/Archive/ArchiveExporterCommandTest.php
**Motivation**
We don't want to be patching Symfony long-term
Simply remove the patch.
I can no longer reproduce whatever issue originally drove us to patch Symfony Filesystem. I'm not sure whether that's because something was fixed in the meantime, or I just don't know what steps to take to reproduce it. I'm hoping it's the former.
3. Run the `archive:export` and `push:artifact` command, which use the affected `mirror()` method. Do this before and after applying the changes in this PR and confirm that the generated …
=> CLI-176: Unpatch Symfony filesystem

src/Command/Env/EnvCreateCommand.php, tests/phpunit/src/Commands/Env/EnvCreateCommandTest.php
**Motivation**
Running `env:create` with interactive branch name selection throws an error
=> CLI-829: env:create error

phpunit.xml.dist, src/AcsfApi/AcsfClientService.php, src/AcsfApi/AcsfCredentials.php, src/ApiCredentialsInterface.php, src/CloudApi/ClientService.php, src/CloudApi/CloudCredentials.php, src/Command/Acsf/AcsfApiAuthLogoutCommand.php, src/Command/Acsf/AcsfApiBaseCommand.php, src/Command/Auth/AuthLoginCommand.php, src/Command/Auth/AuthLogoutCommand.php, src/Command/CommandBase.php, src/Command/Self/ClearCacheCommand.php, src/Command/WizardCommandBase.php, src/Helpers/TelemetryHelper.php, tests/phpunit/bootstrap.php, tests/phpunit/src/AcsfApi/AcsfServiceTest.php, tests/phpunit/src/CloudApi/AccessTokenConnectorTest.php, tests/phpunit/src/CloudApi/CloudServiceTest.php, tests/phpunit/src/Commands/Acsf/AcsfApiCommandTest.php, tests/phpunit/src/Commands/Acsf/AcsfAuthLoginCommandTest.php, tests/phpunit/src/Commands/Acsf/AcsfAuthLogoutCommandTest.php, tests/phpunit/src/Commands/Auth/AuthLoginCommandTest.php, tests/phpunit/src/Commands/Auth/AuthLogoutCommandTest.php, tests/phpunit/src/Commands/CommandBaseTest.php, tests/phpunit/src/TestBase.php
**Motivation**
Access tokens are currently set via the ACLI_ACCESS_TOKEN env var prior to ACLI calls. This is problematic for long-running processes where the token may expire during the process.
Read ACLI_ACCESS_TOKEN_FILE if it is set so that it can be refreshed mid-process if necessary.
=> IDE-2272: Refresh tokens should not expire during ACLI calls

src/Command/Pull/PullCommandBase.php
@anavarre I haven't had time to give this much thought or test it, but it seems to me that this should be coupled to the IDE multisite work. If the customer has enabled multisite, ACLI should use multiple DBs, otherwise it should use a single DB.
This doesn't fix the permissions issue but it at least stops the bleeding. Let me know if you think it's an acceptable hotfix.
=> CLI-842: Restore single-db imports for IDE

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
**Motivation**
Fixes #1152 
Always import to default db in IDEs and refactor the logic to make regressions less likely.
3. Run `pull:db` in an IDE against a multisite application, ensure that it's imported to the default db.
=> IDE-2489: Restore default db import behavior

config/prod/services.yml, src/Command/Acsf/AcsfCommandFactory.php, src/Command/Api/ApiCommandFactory.php, src/Command/CommandBase.php, src/Command/Pull/PullCodeCommand.php, src/Command/Pull/PullCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, src/Command/Pull/PullFilesCommand.php, src/Command/Pull/PullScriptsCommand.php, src/Command/Push/PushArtifactCommand.php, src/Command/Push/PushCodeCommand.php, src/Command/Push/PushDatabaseCommand.php, src/Command/Push/PushFilesCommand.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Acsf/AcsfApiCommandTest.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes CLI-837
Use a plain Guzzle Client request since we're not actually calling the Cloud API the second time but the customer domain directly. This might break some minor features that were dependent on the Cloud client, such as progress reporting, but this seems like a small price to pay to support SSL fallback. Ultimately this is all a problem with Cloud API redirecting download requests instead of streaming them directly (which is what caused the SSL issue in the first place).
Shockingly, it seems we don't make raw Guzzle requests anywhere else in a way that requires mocking, so this requires adding a new service via DI.
Keep abusing the Acquia Cloud Client for the subsequent request like before. Doesn't seem smart. …
=> CLI-837: Broken SSL certs cause pull:db to fail

src/Command/Ide/Wizard/IdeWizardCreateSshKeyCommand.php, src/Command/Ssh/SshKeyCommandBase.php, src/Command/Ssh/SshKeyUploadCommand.php, src/Helpers/SshCommandTrait.php, tests/phpunit/src/Commands/Ssh/SshKeyUploadCommandTest.php
**Motivation**
Fixes CLI-838
- Modify ssh key upload warning message to mention specific times (>1 hour)
- Tell customers to contact support if it takes too long (workarounds would be to re-use an existing key or delete the key and try again, and support should channel this into a PF)
- Add this prompt to SSH key uploads in IDEs for consistency
=> CLI-838: SSH key upload timeouts

composer.json, composer.lock, src/CloudApi/CloudCredentials.php, src/EventListener/ExceptionListener.php, src/Exception/AcquiaCliException.php, tests/phpunit/src/CloudApi/AccessTokenConnectorTest.php, tests/phpunit/src/Commands/Pull/PullFilesCommandTest.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes #1177
Catch this condition and rethrow as an exception so we can track via Amplitude and provide the customer with assistance
3. Set ACLI_ACCESS_TOKEN_FILE or ACLI_ACCESS_TOKEN_EXPIRY_FILE to an invalid value and observe that an exception is thrown instead of a warning.
=> CLI-857: Warning on missing refresh token

.github/workflows/mutation.yml, composer.json, composer.lock, infection.json, src/Command/Remote/AliasesDownloadCommand.php, tests/phpunit/src/Commands/Remote/AliasesDownloadCommandTest.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes #1191
- Match string instead of integer
- Fix tests to cover this case
3. Ensure `remote:aliases:download` works.
=> CLI-863: Fix Drush alias download

src/Command/CodeStudio/CodeStudioPipelinesMigrateCommand.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/App/NewCommandTest.php, tests/phpunit/src/Commands/Email/ConfigurePlatformEmailCommandTest.php, tests/phpunit/src/Commands/Pull/PullCommandTest.php, tests/phpunit/src/Commands/Remote/AliasesDownloadCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyInfoCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyListCommandTest.php, tests/phpunit/src/Misc/LocalMachineHelperTest.php, tests/phpunit/src/TestBase.php
Cuts number of tmp directories on every test run from 600 to 10, I'll take it. Could still fix the rest of the tests to use VFS ideally. And really, stop mirroring the whole fixture for every test, only mock the files we need.
Also need to fix email subscription command to stop creating weird csv directory.
Follow-up from https://github.com/acquia/cli/pull/1195
=> CLI-861: Use virtual fs for tests

composer.lock, src/Command/CodeStudio/CodeStudioCommandTrait.php, src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioPipelinesMigrateCommandTest.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
**Motivation**
Fixes #1192 
Shows cs:wizard in the acli command list.
3. Run `./bin/acli` and see `codestudio:wizard` in the list of available commands.
=> CLI-864 | Unhide cs:wizard from list of ACLI commands

composer.json, composer.lock, config/prod/services.yml, src/AcsfApi/AcsfConnector.php, src/CloudApi/AccessTokenConnector.php, src/CloudApi/CloudCredentials.php, src/CloudApi/ConnectorFactory.php, src/Command/Auth/AuthLoginCommand.php, src/Command/CodeStudio/CodeStudioPipelinesMigrateCommand.php, src/Command/CodeStudio/CodeStudioWizardCommand.php, src/Command/CommandBase.php
**Motivation**
Allows non-production Cloud API endpoints to be called, which in turn requires using non-production Accounts API.
Add support for `ACLI_CLOUD_API_ACCOUNTS_URI` environment variable to complement `ACLI_CLOUD_API_BASE_URI`. If null, these default to the production endpoints defined in the Acquia PHP SDK. You generally must set both to a matching environment (dev/stage/prod).
4. …
=> IDE-134: Support non-production Accounts API

.github/workflows/ci.yml
I noticed PHP setup on Windows was painfully slow, not sure if something changed recently on the runners, seems like maybe so: https://github.com/shivammathur/setup-php/commit/189e8e6ec0f2daf4e4d26cdfeacdaf52d56b46a9
=> CLI-932: Test on PHP 8.2

src/Command/App/AppVcsInfo.php, tests/phpunit/src/Commands/App/AppVcsInfoTest.php
Fix #1322
Added a new flag `--deployed`
```
➜  ~/projects/acli_git git:(show_only_deployed_vcs) ./bin/acli app:vcs:info --help
Description:
Get all branches and tags of the application with the deployment status
Usage:
app:vcs:info [options] [--] [<applicationUuid>]
app:vcs:info [<applicationAlias>] --deployed
app:vcs:info [<applicationAlias>]
app:vcs:info myapp
app:vcs:info prod:myapp
app:vcs:info abcd1234-1111-2222-3333-0e02b2c3d470
Arguments:
applicationUuid            The Cloud Platform application UUID or alias (i.e. an application name optionally prefixed with the realm)
Options:
--deployed[=DEPLOYED]  Show only deployed branches and tags
-h, --help                 Display help for the given command. When no command is given display help for the list command
-q, --quiet …
```
=> Fix #1322: Adding flag to show only deployed VCS

composer.json
Local compiles are broken unless you run `composer install --no-dev` first, but it sounds like that will be fixed soon: https://github.com/box-project/box/issues/580
=> CLI-936: Upgrade Box

src/Command/CommandBase.php
**Motivation**
ACLI wrongly reports available updates when running commands _other_ than `self-update`, because ACLI doesn't use the same upstream version comparisons as self-update 🙄 
Use the same Comparator as consolidation/self-update. Longer-term, fix this in https://github.com/acquia/cli/issues/1403
1. Follow the [contribution guide](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#building-and-testing) to test the update command, using `2.8.2.0` as the version to replicate the currently-available phar. Ensure that you are not prompted for updates when running commands like `ide:create`.
=> CLI-975: Fix false positive updates

box.json, composer.json, composer.lock
Fix #1325 
I performed manual testing to ensure that the box checker now properly calls out the conflict with psr, and that the phar is still packaged correctly otherwise.
=> CLI-943: Prevent running when PSR extension is enabled

src/Command/Pull/PullCommandBase.php
`str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated`
Reported via bugsnag
=> Deprecation in ide:php-version redispatch

src/Helpers/LocalMachineHelper.php
I don't think PHP should be emitting these warnings in the first place. If they are legitimate (which I don't think they are), it's unclear how to resolve them. https://github.com/php/php-src/issues/10092
=> CLI-1042: Suppress warnings from posix_isatty

Dockerfile
**Motivation**
If I build the [Dockerfile](https://github.com/acquia/cli/blob/main/Dockerfile) and run the resulting image, it tells me:
git clone https://github.com/acquia/cli.git
cd cli
docker build -t acquia-cli .
docker run --rm acquia-cli php /usr/local/bin/acli
```
Box Requirements Checker
========================
> Using PHP 8.1.18
> PHP is using the following php.ini file:
/etc/php81/php.ini
> Checking Box requirements:
.......E.......
[ERROR] Your system is not ready to run the application.                       
Fix the following mandatory requirements:
=========================================
* The package "composer/ca-bundle" requires the extension "openssl". You either
need to enable it or request the application to be shipped with a polyfill
for this extension.
``` …
=> php-openssl is required when building Dockerfile

.github/dependabot.yml
Originally I was thinking of grouping updates by major package (i.e., symfony, guzzle), but now I'm thinking it's better to group everything together. Basically a weekly `composer update`.
Commits become less granular, which makes tracing breaking updates harder, but overall I think the tradeoff is worth it to reduce Git history pollution.
=> CLI-1050: Grouped updates

src/Helpers/SshCommandTrait.php, tests/phpunit/src/Application/ExceptionApplicationTest.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php, tests/phpunit/src/Commands/ClearCacheCommandTest.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioPipelinesMigrateCommandTest.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php, tests/phpunit/src/Commands/Ide/IdeCreateCommandTest.php, tests/phpunit/src/Commands/Ide/Wizard/IdeWizardCreateSshKeyCommandTest.php, tests/phpunit/src/Commands/Remote/SshCommandTestBase.php, tests/phpunit/src/Commands/Ssh/SshKeyCreateUploadCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyDeleteCommandTest.php, tests/phpunit/src/Commands/Ssh/SshKeyUploadCommandTest.php, tests/phpunit/src/Commands/TelemetryCommandTest.php, tests/phpunit/src/Commands/WizardTestBase.php, tests/phpunit/src/TestBase.php
The mock methods are basically all boilerplate, and they are a bit magical and inconsistent in how they handle requests, parameters, and responses.
It might be a little more code, but I'd prefer to reduce the amount of abstraction and have just a single mockRequest method.
=> Refactor mock methods

src/Command/App/TaskWaitCommand.php
**Motivation**
The example usage help output for `app:task-wait` is wrong - it repeats the command separated by `acli`.
Currently (note the second example):
```
Usage:
app:task-wait <notification-uuid>
app:task-wait acli app:task-wait "$(api:environments:domain-clear-caches [environmentId] [domain])"
```
This is due to the hard-coded argument zero (/command name) being passed to `Command::addUsage`. From the `addUsage` method comments:
> Add a command usage example, **it'll be prefixed with the command name**.
Compare the output of `acli help app:task-wait` before and after applying this patch.
Before:
```
app:task-wait acli app:task-wait "$(api:environments:domain-clear-caches [environmentId] [domain])"
```
After:
```
app:task-wait …
```
=> Fixes output of usage example for task-wait command

phpunit.xml.dist, src/Command/App/AppOpenCommand.php, src/Command/Archive/ArchiveExportCommand.php, src/Command/CodeStudio/CodeStudioWizardCommand.php, src/Command/CommandBase.php, src/Command/Pull/PullCodeCommand.php, src/Command/Pull/PullCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, src/Command/Pull/PullFilesCommand.php, src/Command/Pull/PullScriptsCommand.php, src/Command/Push/PushDatabaseCommand.php, src/Command/Push/PushFilesCommand.php, src/Helpers/LocalMachineHelper.php, tests/phpunit/bootstrap.php, tests/phpunit/src/Application/KernelTest.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/App/AppOpenCommandTest.php, tests/phpunit/src/Commands/App/AppVcsInfoTest.php, tests/phpunit/src/Commands/ClearCacheCommandTest.php, tests/phpunit/src/Commands/CommandBaseTest.php, tests/phpunit/src/Commands/Email/EmailInfoForSubscriptionCommandTest.php, tests/phpunit/src/Commands/Ide/IdeDeleteCommandTest.php, tests/phpunit/src/Commands/Ide/IdeInfoCommandTest.php, tests/phpunit/src/Commands/Ide/IdeListCommandTest.php, tests/phpunit/src/Commands/Ide/IdeOpenCommandTest.php, tests/phpunit/src/Commands/Ide/IdeShareCommandTest.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php, tests/phpunit/src/Commands/Push/PushFilesCommandTest.php, tests/phpunit/src/TestBase.php
Fix #1386 
@mikemadison13 @anavarre any opinions about this as a solution to avoiding confusion about documented commands?
Most of the hidden commands (i.e., `pull:files`) were only hidden because they required a db connection that was only set in an IDE. But we now have environment variables like ACLI_DB_HOST that anyone could set locally if they really wanted.
This unhides those commands and instead advises via help text that these variables should be set:
We still hide truly IDE-specific commands (i.e., `ide:service-restart`). Hopefully the reason is obvious enough that people aren't still confused.
=> CLI-1054: Support pull commands outside of IDEs

src/Command/CommandBase.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php
Right now if you pass an email address as user alias and that email doesn't match someone in the org you get a confusing error message from the API:
```
{
"error": "invalid_id",
"message": "\"somebody@danepowell.com\" is not a valid v4 UUID."
}
```
ACLI should not pass an argument to the API that it knows to be invalid (i.e., not a UUID).
@joshirohit100 would you mind reviewing since you wrote this?
=> Throw exception if userAlias not found

src/Command/App/TaskWaitCommand.php, src/Command/CommandBase.php, tests/phpunit/src/Commands/App/TaskWaitCommandTest.php
**Motivation**
Fixes #1556 
Returns an exit code `1` when a notification executed via `task-wait` has any status other than `completed`.
One could alternatively retrieve the notification UUID from the initial command response, run `task-wait` with that, and then use `api:notifications:find` to confirm task completed.
From `main` attempt to `code-switch` an environment to a non-existent branch. Observe the notification fails and the exit code is `0`.
```
> acli -nq app:task-wait "$(acli -n api:environments:code-switch "$ACQUIA_SITE_GROUP".prod "$RELEASE_TAG")"
Acquia CLI 2.12.3 is available. Run acli self-update to update.
✔ Waiting for task d109e8f6-bed1-4fa4-bc28-4b57f5030a36 to complete
[ERROR] The task with notification …
```
=> CLI-1101: Set exit code 1 when a task waited command fails

src/Command/App/TaskWaitCommand.php, src/Command/CommandBase.php, src/Command/Env/EnvCertCreateCommand.php, src/Command/Env/EnvCreateCommand.php, src/Command/Env/EnvMirrorCommand.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Acsf/AcsfAuthLoginCommandTest.php, tests/phpunit/src/Commands/App/TaskWaitCommandTest.php
**Motivation**
Fixes #1558
Anywhere that a notification UUID is required as argument, support passing a notification object or URL as well. This basically generalizes the `getNotificationUuid` logic in app:task-wait to all commands.
3. Try `acli app:task-wait` with various forms of arguments to ensure they still work:
```
wacli app:task-wait "$(acli api:environments:domain-clear-caches …
```
=> CLI-1103: Fix #1558: Notification arg formats

src/Command/App/NewFromDrupal7Command.php
**Motivation**
#1543 added `acli app:new:from:drupal7`. 👍  Next steps in open sourcing: https://git.drupalcode.org/project/acquia_migrate/-/tree/recommendations is live.
So now let's get it all working together. Unfortunately, this made me hit an edge case in GitLab and/or PHP.
Ideally, we'd get the command to automatically download the latest, to allow you to omit `--recommendations`. But as an MVP, we can do:
```
./bin/acli app:new:from:drupal7 --directory=/tmp/foo --recommendations=https://git.drupalcode.org/project/acquia_migrate/-/raw/recommendations/recommendations.json --stored-analysis tests/fixtures/drupal7/training.acquia.com/extensions.json 
```
Unfortunately, this is the output:
```
🤖 Scanning Drupal 7 site.
👍 Found Drupal 7 site (7.70 to be precise) at <location unknown>, …
```
=> d.o's GitLab instance 403s if `User-Agent` is absent or empty

src/Command/App/NewFromDrupal7Command.php
**Motivation**
#1543 added `acli app:new:from:drupal7`. 👍  Next steps in open sourcing: https://git.drupalcode.org/project/acquia_migrate/-/tree/recommendations is live.
So now let's get it all working together. Unfortunately, this made me hit an edge case in GitLab and/or PHP. I opened #1587 for that.
**Ideally, we'd get the command to automatically download the latest, to allow you to omit `--recommendations`.**
That'd be a much better UX than having to specify a long URL manually.
Defaulting to automatically downloading the latest is a one-line change:
```
-    $recommendations_location = __DIR__ . '/../../../config/from_d7_recommendations.json';
+    $recommendations_location = "https://git.drupalcode.org/project/acquia_migrate/-/raw/recommendations/recommendations …
```
=> Make `acli app:new:from:drupal7` default to the latest AMA recommendations on d.o

config/from_d7_config.json
**Motivation**
For historical reasons, the predecessor of `acli app:new:from:drupal7` had to hardcode the package containing the AM:A Drupal module.
That is still there. It's never gotten in the way.
Until now.
Because `config/from_d7_config.json` is hardcoded to list `acquia/acquia-migrate-accelerate` in its project template, the recommendations that we will have at https://git.drupalcode.org/project/acquia_migrate/-/tree/recommendations will generate a project that continues to install the packagist/closed source AMA retrieved from GitHub instead of the open source AMA source retrieved from d.o’s packagist facade.
IOW, both of these will exist in the generated `composer.json`:
- `acquia/acquia-migrate-accelerate` 
- `drupal/acquia_migrate` (once it exists)
Clearly we shouldn't install …
=> Make `acli app:new:from:drupal7` defer entirely to the recommendations

.github/workflows/ci.yml
**Motivation**
There were a couple of changes in shivammathur/setup-php (specifically [#754](https://github.com/shivammathur/setup-php/commit/a5fb328c6a38ac8086676fc64e6e78a39d6ef69e)) which resulted in new builds using [PHP 8.0 during the build](https://github.com/acquia/cli/actions/runs/6263194877/job/17007030360#step:6:379) step.
This change explicitly sets the php version to be used.
None
The build step will fail (example) without this with:
```
"Error: ] Your system is not ready to run the application.                       
Fix the following mandatory requirements:
=========================================
* The application requires a version matching "^8.1"."
``` 
And it will pass with this PR merged.
=> Explicitly set php version to be used during CI build

src/Command/CodeStudio/CodeStudioCiCdVariables.php, tests/phpunit/src/CommandTestBase.php
**Motivation**
Recently we found that code studio environment variables like `TOKEN_KEY, TOKEN_SECRET` are being logged in  sumo logic in plain text format, which is a security concern.
Fixes GL-1377
In order to avoid logging env variable values in clear text format, we will be masking code studio default env variable.
In this PR we will setting all default env variable values as `masked`.
You can replicate this issue by creating a new project for code studio and check the env variables values under CI/CD variable. You will see currently default env values is not masked except `ACQUIA_GLAB_TOKEN_SECRET`.
Once these changes are deployed then you can verify the changes by creating a new project for code studio and run a …
=> Set code studio default env variable values to be masked

src/Command/CodeStudio/CodeStudioCiCdVariables.php, src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes # GL-1836
Add a prompt to choose php version between two of them. Either 8.1 or 8.2
run command `./bin/acli cs:wizard` and CLI should ask to choose PHP version. Once steps are completed then verify PHP_VERSION variable should get added to code studio UI.
=> Added prompt for php version for cs:wizard command

composer.json, composer.lock
This may fix type errors that some people see related to the Box requirements checker in some terminals, especially Git Bash. See https://github.com/box-project/box/pull/999
=> CLI-1039: Update box, fix typeerror in some terminals

src/Command/Push/PushArtifactCommand.php
**Motivation**
push:artifact doesn't mirror symlinks that point to directories. It probably also doesn't mirror empty directories, though that's less likely to cause problems since empty directories are VCS ignored and not generally useful anyway.
=> CLI-1136: [push:artifact] include empty directories and symlinks

src/Helpers/LocalMachineHelper.php, tests/phpunit/src/Misc/LocalMachineHelperTest.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes #1610 
extending env variable testing condition to avoid PHP error when the var is not present
=> CLI-1171: Home directory errors on Windows

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullCodeCommandTest.php
**Motivation**
For certain applications and environments, `composer install` can fail when composer dependencies are already installed
Don't run composer install if dependencies are already installed; i.e., for build branches.
=> CLI-1181: [pull:code] disable scripts for build branches

config/prod/services.yml, src/Command/Auth/AuthAcsfLogoutCommand.php
cloudApiClientService should be an instance of AcsfClientService but it's not. I can't figure out how to wire up the service container to make that work.
It's easy enough to do without it though.
=> CLI-1175: [auth:acsf-logout] undefined array key

src/Command/CommandBase.php
**Motivation**
I was trying to deploy code from a repo to a new application not already linked to that repo and was confused when it produced a Cloud API error because it was inferring the app id from .acquia-cli.yml rather than the more explicit env id.
=> CLI-1217: push:artifact should infer app id from env id

src/Command/CommandBase.php, tests/phpunit/src/Commands/InferApplicationTest.php, tests/phpunit/src/Commands/Ssh/SshKeyUploadCommandTest.php
This has the side effect of throwing an exception when the Git config is invalid or missing, as opposed to before when it might still fall back to other methods of finding the application. I think it's a desirable change.
=> CLI-1221: TypeError and warning in remote:alises:download

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
**Motivation**
Fixes #1640: The pull:database command fails silently if pv is not installed
if pv is not installed, run gunzip with the -c flag so the decompressed output is piped to the mysql command
There are other possible ways to manage output redirection in bash, this seemed simplest.
On a system without pv installed set the appropriate ACLI_DB_**** environmental variables and execute an acli pull:database request. See the database downloaded and the command appear to succeed. Open the database and see that it is not empty.
1. Follow the [contribution guide](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#building-and-testing) to set up your development environment or [download a pre-built …
=> CLI-1225: The pull:database command fails silently if pv is not installed.

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Archive/ArchiveExporterCommandTest.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php, tests/phpunit/src/Commands/Push/PushDatabaseCommandTest.php
Fixes #1629 
Fixes #1634 
Note, this has the side effect of no longer creating a db if it doesn't already exist.
=> CLI-1210: Drop tables instead of database

.phpstorm.meta.php, assets/acquia-spec.yaml, src/Command/Auth/AuthLoginCommand.php, tests/phpunit/src/Commands/Acsf/AcsfApiCommandTest.php, tests/phpunit/src/Commands/Auth/AuthLoginCommandTest.php, tests/phpunit/src/TestBase.php
=> CLI-1219: API key labels should be email addresses

src/Command/Self/MakeDocsCommand.php
**Motivation**
Opens up options to render docs in other formats while maintaining current approach.
Add an option for format.
=> Allow other descriptor formats to be used to render docs.

.github/workflows/ci.yml, src/Command/Auth/AuthLoginCommand.php, src/Command/Self/ClearCacheCommand.php, src/Command/Self/MakeDocsCommand.php
This can't really be tested except in master
=> CLI-1237: Publish docs

src/Command/CommandBase.php, src/Command/Ide/Wizard/IdeWizardCommandBase.php, src/Command/Ide/Wizard/IdeWizardCreateSshKeyCommand.php, src/Command/Ssh/SshKeyCommandBase.php, tests/phpunit/src/Commands/Ide/IdeDeleteCommandTest.php, tests/phpunit/src/Commands/Ide/IdeHelper.php, tests/phpunit/src/Commands/Ide/Wizard/IdeWizardCreateSshKeyCommandTest.php, tests/phpunit/src/Commands/Ide/Wizard/IdeWizardDeleteSshKeyCommandTest.php, tests/phpunit/src/TestBase.php
**Motivation**
This API call is unnecessary. More importantly, it makes QA of IDE changes difficult because it's the only API call to the IDE endpoint associated with IDE creation.
Use REMOTEIDE_LABEL instead of calling the API.
3. Run `ide:wizard` in a new IDE, see that an SSH key is created successfully with the same label as before.
=> CLI-1245: Use REMOTEIDE_LABEL to bypass API call

src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
=> CLI-1257: pull:db fails with too many tables

.phpstorm.meta.php, src/Command/App/LogTailCommand.php, src/Command/CodeStudio/CodeStudioWizardCommand.php, src/Command/CommandBase.php, src/Command/Env/EnvCertCreateCommand.php, src/Command/Env/EnvCopyCronCommand.php, src/Command/Push/PushDatabaseCommand.php, src/Command/Remote/DrushCommand.php, tests/phpunit/src/Application/ExceptionApplicationTest.php, tests/phpunit/src/Application/KernelTest.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/App/LogTailCommandTest.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php, tests/phpunit/src/Commands/Pull/PullFilesCommandTest.php, tests/phpunit/src/Commands/Push/PushDatabaseCommandTest.php, tests/phpunit/src/Commands/Push/PushFilesCommandTest.php, tests/phpunit/src/Commands/Remote/DrushCommandTest.php
I let refactoring get the best of me on this one, but it's for the better... not only does this allow several commands to be run with the standard environment prompt, I think this actually fixes a similar bug on ACSF environments with numeric prefixes (01dev). I confirmed that the expected directories in that case are `/var/www/site-php/profserv2.01dev`, not `/var/www/site-php/profserv2.dev` as our code and tests previously expected.
=> CLI-1272: remote:drush fails with realm alias

src/EventListener/ComposerScriptsListener.php, tests/phpunit/src/Application/ComposerScriptsListenerTest.php, tests/phpunit/src/Application/ExceptionApplicationTest.php
**Motivation**
Fixes #1276
Passing `--no-scripts` to any command that supports it will disable Composer command hooks.
3. Run a command such as `acli pull:code --no-scripts -v`.
4. Verify you don't see any messages in the output about composer scripts.
=> CLI-1276: no-scripts doesn't disable composer hooks

src/Command/CommandBase.php, src/Command/Ide/IdeShareCommand.php, tests/phpunit/src/Commands/Ide/IdeShareCommandTest.php
**Motivation**
This API call is unnecessary and hinders testing, let's simplify it.
Use env var instead.
3. Check for regressions in `acli ide:share`
=> CLI-1263: [ide:share] remove unnecessary API call

src/Command/Remote/DrushCommand.php, tests/phpunit/src/Commands/Remote/DrushCommandTest.php
**Motivation**
As a manager of a dozen applications at Acquia, I want to use `acli remote:drush` to perform routine tasks (especially `uli` login) on multiple remote applications without remembering to type the correct `--uri` every time. Previously with Drupal 7/drush 8/Acquia Cloud API v1 one could use `drush acquia-update` to easily keep local aliases up-to-date, but this is no longer an option.
Since `remote:drush` is already fetching the Acquia environment information behind the scenes for the alias provided, it should pass along the `default_domain` parameter when none is given by the user. Allow the user to continue to provide their own `--uri` parameter if the default isn't sufficient (on a drush command, the last duplicate parameter wins).
**Alternatives …
=> Pass default domain to remote drush command

src/Command/Auth/AuthLoginCommand.php, tests/phpunit/src/Commands/Auth/AuthLoginCommandTest.php
I couldn't find any reason in the code for the datastore to be corrupted... presumably someone mucking with cloud_api.conf
=> CLI-1290: [auth:login] php warning

src/Command/CommandBase.php, src/Command/Ide/IdeCreateCommand.php, src/Helpers/LoopHelper.php, tests/phpunit/src/Commands/Ide/IdeCreateCommandTest.php
We were swallowing the CloudApiException that would otherwise alert the user to the invalid notification id.
=> CLI-1286: [app:task-wait] typeerror for invalid notification uuid

.phpstorm.meta.php, src/EventListener/ExceptionListener.php, tests/phpunit/src/Application/ExceptionApplicationTest.php
@anavarre your opinion on messaging?
Typically a type error does indicate a problem with the application, i.e. some kind of broken configuration or environment. Sometimes it's a more general problem, which is actually true for CLI-1292. There's nothing wrong with the customer application in CLI-1292; the API will pretty much always return cron information that violates the published spec.
=> CLI-1292: Catch Cloud API type errors

src/Command/Auth/AuthLoginCommand.php, tests/phpunit/src/Commands/Auth/AuthLoginCommandTest.php
**Motivation**
When using the latest version of acli which is 2.23.1 the command auth:login [-k|--key KEY] [-s|--secret SECRET] no longer works and generates the following error. This occurs when `acli -n telemetry:disable` is set before auth for CI/CD pipelines.
The issue is triggered during CI/CD pipeline by set some settings for the CLI before auth function such as switching on/off the telemetry.
Fixes #1708 
if condition fix, update the cli only.
reduce the number of required changes in code
1. Follow the [contribution guide](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#building-and-testing) to set up your development environment or [download a pre-built …
=> CLI-1296: auth:login on 2.23.1 > Invalid key in Cloud datastore fixed

src/Helpers/LocalMachineHelper.php
See also https://github.com/php/php-src/pull/13821
=> CLI-1268: Suppress posix warnings

src/Application.php, src/Command/Auth/AuthLoginCommand.php, src/Command/Auth/AuthLogoutCommand.php, src/EventListener/ExceptionListener.php, tests/phpunit/src/Commands/Auth/AuthLoginCommandTest.php, tests/phpunit/src/Commands/Auth/AuthLogoutCommandTest.php, tests/phpunit/src/Misc/ExceptionListenerTest.php
@anavarre I'm trying to emphasize the self-help instructions for known exceptions by adding a bold "How to fix it" header, since it's otherwise easy to overlook. How do you feel about this?
For general exceptions where we can't offer specific help, you get just the second and third sentences about docs and support.
=> CLI-1294: [auth:logout] warning when key is invalid

src/Command/Ssh/SshKeyCommandBase.php
Solves null pointer exceptions and is generally cleaner
=> Convert loopy to static methods

src/Command/Api/ApiBaseCommand.php, tests/phpunit/src/Commands/Api/ApiBaseCommandTest.php
For some reason people were actually running this command, and it throws typeerrors that get reported.
=> CLI-1317: api:base is not a valid command

src/Command/CodeStudio/CodeStudioWizardCommand.php
This PR contain changes to support PHP 8.3 version for `acli cs:wizard` command for code studio.
Testing Steps:
Ran acli cs:wizard command locally and got an option to select php version 8.3
Logged in to code studio UI and check for CI/CD variable for project, PHP_VERSION env variable is being set as 8.3.
=> GL-2530 : PHP 8.3 support for CodeStudio

src/Command/Auth/AuthLoginCommand.php, src/Command/Auth/AuthLogoutCommand.php, src/Config/CloudDataConfig.php, src/DataStore/Datastore.php, src/EventListener/ExceptionListener.php, tests/phpunit/src/Commands/Auth/AuthLoginCommandTest.php, tests/phpunit/src/Commands/Auth/AuthLogoutCommandTest.php, tests/phpunit/src/Misc/ExceptionListenerTest.php
Unfortunately validation exceptions occur during container builds and therefore bypass our lovely error handler. Not much we can do about that except to write a whole new error handler just for the container build step.
=> CLI-1334: TypeError in auth:login

src/Helpers/TelemetryHelper.php, tests/phpunit/src/Misc/TelemetryHelperTest.php
**Motivation**
We often don't know if ACLI is running in Code Studio, on local, or elsewhere.
Add an "env_provider" data point to telemetry, based on env variables, to determine env provider.
=> Track environment provider in telemetry.

src/Kernel.php
=> CLI-1336: Isolate cache dir per test

src/Command/CodeStudio/CodeStudioCommandTrait.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
**Motivation**
After gitlab upgrade to v17.0, cs-wizard started failing due to one of bug fix by gitlab which allows scheduling pipelines even when project has no branch. 
Project will have default branch main on which schedule pipelines can be configured.
Tried executing cs-wizard command project creation works fine with latest upgrade.
=> GL-2639: Initialise project with default branch and readme file.

src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
As of now schedule pipelines are configured for both node projects and drupal projects. But those are only required for Drupal Projects. Hence removing it from node projects.
Manual tests:
1. With the Node project selected in the `cs:wizard` command, the resultant Node project in Gitlab should not have a pre-configured scheduled pipeline
2. Regression test: With this update, the Drupal selection flow should not be impacted (i.e. creation, variables etc. along with a configured scheduled pipeline should be validated)
=> GL-2582 : Remove schedule pipelines for node projects

composer.json, composer.lock
=> CLI-19: [self-update] respect proxy settings

src/Command/CommandBase.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Push/PushDatabaseCommandTest.php
Turns out we aren't the first ones to have this problem: https://github.com/drush-ops/drush/issues/3816
If Drush does it this way, it's good enough for me! 😄 
Testing steps:
- Set max_allowed_packet extremely low, or import a db with huge row sizes
- Run `push:db -vvv`
Before this PR, see that the push continues past the local dump despite an error about packet size. After this error, see that the push stops with the following exception:
```
In CommandBase.php line 1703:
[Acquia\Cli\Exception\AcquiaCliException]       
Unable to create a dump of the local database.  
```
=> CLI-1362: [push:db] mysqldump failure not surfaced

src/EventListener/ExceptionListener.php, tests/phpunit/src/Misc/ExceptionListenerTest.php
=> CLI-1327: Handle corrupt db

src/Command/Env/EnvCertCreateCommand.php, src/Command/Env/EnvCreateCommand.php, src/Command/Env/EnvMirrorCommand.php, src/Command/Pull/PullCommandBase.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Env/EnvCertCreateCommandTest.php, tests/phpunit/src/Commands/Env/EnvCreateCommandTest.php, tests/phpunit/src/Commands/Env/EnvMirrorCommandTest.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php
**Motivation**
Fixes warnings when a backup (or any other Cloud API task) fails
Check the notification response to make sure the task completed successfully
=> CLI-1370: PHP warning in pull:db when backup fails

src/Helpers/TelemetryHelper.php
=> CLI-1380: Stop reporting memory exhaustion

src/Command/Push/PushArtifactCommand.php
I have noticed about the confusion to push / use multiple git remotes the artifact.
This MR is adding an example/usage  in command help for same.
Will this automatic generate / update doc https://docs.acquia.com/acquia-cloud-platform/add-ons/acquia-cli/commands/push:artifact or thats separate?
=> Example to support / Push to multiple git remotes.

src/Command/Push/PushArtifactCommand.php, src/Config/AcquiaCliConfig.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php
=> CLI-1389: push.artifact.destination_git_urls in acquia cli config

tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/App/AppOpenCommandTest.php, tests/phpunit/src/Commands/App/LinkCommandTest.php, tests/phpunit/src/Commands/App/UnlinkCommandTest.php, tests/phpunit/src/Commands/CommandBaseTest.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php, tests/phpunit/src/Commands/Remote/AliasesDownloadCommandTest.php, tests/phpunit/src/Commands/TelemetryCommandTest.php, tests/phpunit/src/TestBase.php
**Motivation**
Fixes CLI-1389
Improve tests to catch validation errors in datastores to prevent regressions like CLI-1389
Calling set() on a keystore doesn't trigger validation. Validation only occurs when the contents of the datastore file are loaded from disk. So test cases should never use set() for configuring a test fixture, but rather write the file and reload the command/datastore.
3. …
=> CLI-1389: Catch datastore validation errors in tests

src/Command/Push/PushArtifactCommand.php
**Motivation**
Fixes #1787 
Fixes CLI-1388
Deprecate `--source-git-tag`. If `--destination-git-branch` is set, use it for the same purpose.
=> CLI-1388: Deprecate source-git-tag

src/Command/Ssh/SshKeyCommandBase.php
**Motivation**
Fixes CLI-1397
Remove the check for RSA keys
It looks like this was added in #1501 because we simply copied the code from the upstream library: https://github.com/violuke/rsa-ssh-key-fingerprint/blob/master/src/violuke/RsaSshKeyFingerprint/FingerprintGenerator.php
But I can't see any reason to restrict that code to RSA keys. You can run sha256 on any key 🤷 
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli …
=> CLI-1397: Exception on local non-RSA SSH keys

.github/workflows/ci.yml, tests/phpunit/src/Misc/ChecklistTest.php, tests/phpunit/src/Misc/LocalMachineHelperTest.php
**Motivation**
These tests fail frequently in CI, and only in PHP 8.3. No idea why... possibly a race condition, or i/o issues, or an issue caused by paratest.
Run these tests in serial.
=> CLI-1405: LocalMachineHelperTest::testExecuteFromCmd failure

src/Command/CommandBase.php, src/Command/Self/SelfInfoCommand.php, src/Command/Self/SelfStatusCommand.php, src/Helpers/TelemetryHelper.php, tests/phpunit/src/Application/KernelTest.php, tests/phpunit/src/Commands/Self/ClearCacheCommandTest.php, tests/phpunit/src/Commands/Self/SelfInfoCommandTest.php, tests/phpunit/src/Commands/Self/TelemetryCommandTest.php, tests/phpunit/src/Commands/Self/TelemetryDisableCommandTest.php, tests/phpunit/src/Commands/Self/TelemetryEnableCommandTest.php
**Motivation**
Fixes CLI-1410
Add a `self:info` command to provide debugging information for support tickets
Provide debugging info inline with individual commands when running with `-vvv`. This could be unnecessarily verbose or expose mildly sensitive information, but would save customers an extra step. Most modern applications have a standalone command for generating debug logs and reports though.
2. Clear the kernel cache to pick up new and …
=> CLI-1410: self:info command

.editorconfig, phpcs.xml.dist
**Motivation**
Fixes CLI-1413
Set compatibility level according to https://github.com/acquia/coding-standards-php/pull/37
=> CLI-1413: Set PHP compatibility level

src/Command/CodeStudio/CodeStudioWizardCommand.php
**Motivation**
[GL-3083](https://acquia.atlassian.net/browse/GL-3083)
The default version on PHP while running the cs-wizard command is now updated to 8.3 
Following steps can be taken to verify the changes:
- Run the following command `acli cs:wizard`.
- Please enter Cloud Key and Secret to login
- Select the type of project as Drupal
- In the PHP version select step the default value will be 8.3
=> GL-3083: cs-wizard updated default php version to 8.3

composer.json, composer.lock, src/Attribute/RequireLocalDb.php, src/Attribute/RequireRemoteDb.php, src/Command/Archive/ArchiveExportCommand.php, src/Command/CommandBase.php, src/Command/Pull/PullCodeCommand.php, src/Command/Pull/PullCommand.php, src/Command/Pull/PullCommandBase.php, src/Command/Pull/PullDatabaseCommand.php, src/Command/Push/PushDatabaseCommand.php, src/EventListener/ExceptionListener.php, tests/phpunit/src/Commands/Pull/PullCommandTestBase.php, tests/phpunit/src/Commands/Pull/PullDatabaseCommandTest.php, tests/phpunit/src/Commands/Push/PushDatabaseCommandTest.php, tests/phpunit/src/Misc/ExceptionListenerTest.php
**Motivation**
Fixes CLI-1402
- Update SDK to not throw a type error if connection details are missing so we can fail gracefully: https://github.com/typhonius/acquia-php-sdk-v2/pull/477
- Specifically check if details are missing and throw an exception if so (along with help text)
- Add a `RequireRemoteDb` attribute to warn users (via command help) that these perms are required
3. Create a Cloud …
=> CLI-1402: [push:db] Warn if view database connection details permission is missing

src/Command/Push/PushArtifactCommand.php, tests/phpunit/src/Commands/Push/PushArtifactCommandTest.php
=> CLI-1342: [push:artifact] improve docs

src/Command/CodeStudio/CodeStudioCiCdVariables.php, src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioCiCdVariablesTest.php
**Motivation**
Fixes [GL-3134](https://acquia.atlassian.net/browse/GL-3134)
New Node.js projects created in Code Studio pass a new variable of `NODE_HOSTING_TYPE` with a default value of `basic`. When Node V3 launches, we will update the user prompts to ask for a Node hosting type.
N/A
3. Run `acli cs:wizard --gitlab-host-name=code.dev.cloudservices.acquia.io` (or other …
=> GL-3134: Add new Gitlab variable for Node projects.

composer.json, composer.lock, src/Command/Api/ApiBaseCommand.php, src/EventListener/ExceptionListener.php, tests/phpunit/src/CommandTestBase.php, tests/phpunit/src/Commands/Api/ApiCommandTest.php, tests/phpunit/src/Commands/Remote/DrushCommandTest.php, tests/phpunit/src/Misc/ExceptionListenerTest.php, tests/phpunit/src/Misc/LocalMachineHelperTest.php, tests/phpunit/src/TestBase.php
=> CLI-1365: Warn when logs need to be created

src/Command/CommandBase.php, src/Command/Push/PushArtifactCommand.php, src/Command/Ssh/SshKeyCommandBase.php, src/EventListener/ExceptionListener.php
=> CLI-1417: TypeError when applications are not provisioned

src/Command/Self/MakeDocsCommand.php, tests/phpunit/src/Commands/Self/MakeDocsCommandTest.php
**Motivation**
Fixes CLI-1406
Ideally we'd fix or extend the JsonDescriptor instead of handling this in post-processing. Unfortunately, all the JsonDescriptor methods are private and the Descriptor base class is marked as internal.
4. Check new functionality: (add specific steps for this …
=> CLI-1406: Command documentation markup

src/Command/App/NewCommand.php, tests/phpunit/src/Commands/App/NewCommandTest.php
=> CLI-1396: [app:new:local] Add project template option

src/Command/CommandBase.php, src/Command/Pull/PullCommandBase.php, tests/phpunit/src/Commands/Pull/PullCommandTest.php, tests/phpunit/src/Commands/Pull/PullFilesCommandTest.php, tests/phpunit/src/Commands/Push/PushFilesCommandTest.php
If your site has multiple databases, acli pull:db --no-interaction will not pull the default database, which is the logical default.
**Motivation**
Ran into this issue using `ddev pull acquia` on a site with multiple databases.
https://github.com/ddev/ddev/blob/master/pkg/ddevapp/dotddev_assets/providers/acquia.yaml#L53
It wasn't pulling the default, which I would expect.
Use the default site when non-interactive.
Try `acli pull:db --no-interaction` on a site with multiple databases.
1. Follow the [contribution guide](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#building-and-testing) to set up your development environment or [download a pre-built acli.phar](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md# …
=> CLI-1473: Pull default site if non-interactive.

src/Command/App/NewCommand.php, tests/phpunit/src/Commands/App/NewCommandTest.php
**Motivation**
Adds Drupal CMS to the list of scaffold projects.
""
None
`acli app:new:local` should show three options including Drupal CMS.
=> Add option for bootstrapping new site with Drupal CMS

composer.json, composer.lock
=> CLI-1466: Bugsnag-php  minimum version bumped 3.29.2

src/Command/Remote/AliasListCommand.php, tests/phpunit/src/Commands/Remote/AliasesListCommandTest.php
Adding  **SSH URL** column for the drush alias list.
**Impacted command** - `acli remote:aliases:list`
**Context** - We can ssh on server using `acli remote:drush ssh`. I needed to download some file (basically `scp`) from the server to local but I didnt have the details of the ssh of server to do the scp as SCP.
So I think it will be helpfull if drush alias list also provide this details so that this can be used if required
**Output before** -
```
+-----------------------------------+-------------------+--------------------------------------------+
| Application                       | Environment Alias      |   Environment UUID                           |
+-----------------------------------+-------------------+--------------------------------------------+
| My Application …
```
=> CLI-1485: Add SSH URL in alias list

composer.json, composer.lock
=> CLI-1462: Remove league/oauth2-client dependency

src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
**Motivation**
Addresses [GL-3070](https://acquia.atlassian.net/browse/GL-3070)
Adds PHP 8.4 as a prompt option during the `cs:wizard` command.
1. Locally, run `glab auth login --hostname=code.dev.cloudservices.acquia.io`
2. Run `export GITLAB_HOST=code.dev.cloudservices.acquia.io`
3. Run `./bin/acli cs:wizard`
4. Answer prompts until you see the prompt for `Select a PHP version`. Note 8.4 is now an option.
5. Note: 8.3 is still the default selection per Out of Scope section in [FR-2809](https://acquia.atlassian.net/browse/FR-2809)
=> GL-3070: PHP 8.4 support for Code Studio.

src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
**Motivation**
Addresses [GL-3465](https://acquia.atlassian.net/browse/GL-3465)
Adds Node 22 as a prompt option during the cs:wizard command.
N/A
1. Locally, run `glab auth login --hostname=code.dev.cloudservices.acquia.io`
2. Run `export GITLAB_HOST=code.dev.cloudservices.acquia.io`
3. Run `./bin/acli cs:wizard`
4. Answer prompts until you see the prompt for `Select a NODE version`. Note 22 is now an option.
=> GL-3465: Node 22 support for Code Studio.

src/Command/Ssh/SshKeyDeleteCommand.php, src/Helpers/SshCommandTrait.php, tests/phpunit/src/Commands/Ssh/SshKeyDeleteCommandTest.php
**Motivation**
The command should ideally execute when SSH key UUID and labels are specified, rather than prompting the user to select an SSH key from a list. This change would enable the use of command options `cloud-key-uuid` and `label`.
**Fixes**
- Enables the use of existing option `cloud-key-uuid`
- Adds new option `label`
- If only the SSH key's UUID is provided, the command will prompt for a label. It will then search for the key using the given UUID and label and execute the delete operation.
- If both the label and UUID are provided, the delete operation will be executed (if found the key having same UUID & label).
- If none of the options are given, it still works the same way.
**Test case** is also altered the include the options during command execution. …
=> [ssh-key:delete] Enable cloud-key-uuid & label options.

src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
**Motivation**
Resolves [GL-3584](https://acquia.atlassian.net/browse/GL-3584)
In `cs:wizard`, removes version 18 as a node version option. This is due to Acquia removing Node 18 support on April 15, 2025.
N/A
- Locally, run glab auth login --hostname=code.dev.cloudservices.acquia.io
- Run export GITLAB_HOST=code.dev.cloudservices.acquia.io
- Run ./bin/acli cs:wizard
- Answer prompts, ensuring to select an application type of node, until you see the prompt for node version. You should only see options for Node 20 and 22.
=> GL-3584: Remove Node 18 as an option in cs:wizard.

src/Command/CodeStudio/CodeStudioCiCdVariables.php, src/Command/CodeStudio/CodeStudioWizardCommand.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioCiCdVariablesTest.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioPipelinesMigrateCommandTest.php, tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
**Please wait to merge & release until Code Studio team gives the ok.**
**Motivation**
Addresses [GL-3695](https://acquia.atlassian.net/browse/GL-3695)
Adds a prompt for MySQL version to Drupal projects.
N/A. This will become a required variable for all Drupal projects, so we should set it upon project setup.
- Locally, run `glab auth login --hostname=code.dev.cloudservices.acquia.io`
- Run `export GITLAB_HOST=code.dev.cloudservices.acquia.io`
- Run `./bin/acli cs:wizard`
- Answer prompts, ensuring to select an application type of Drupal, until you see the prompt for MySQL version.
- Confirm the variable is added to the Code Studio project upon completion of `cs:wizard`.
=> GL-3695: Add MySQL version prompt for cs:wizard.

assets/acquia-spec.json, src/Command/Acsf/AcsfListCommandBase.php, src/Command/Api/ApiCommandHelper.php, src/Command/Api/ApiListCommandBase.php, tests/phpunit/src/Commands/Acsf/AcsfListCommandTest.php, tests/phpunit/src/Commands/Api/ApiListCommandTest.php
**Motivation**
Fixes CLI-1584
This isn't perfect, it still prints the namespaces for the hidden commands due to a bug in the Symfony ApplicationDescription Descriptor, but it's better than what we have now.
=> CLI-1584: Deprecate MEO endpoints, fix environment command

.github/workflows/ci.yml, .github/workflows/integration-tests.yml, composer.json, composer.lock
**Motivation**
Fixes CLI-1450
Remove support for PHP 8.1 in anticipation of Oct 6 EOL
=> CLI-1450: Drop support for PHP 8.1

src/Command/App/NewCommand.php, tests/phpunit/src/Commands/App/NewCommandTest.php
**Motivation**
Next ACMS hasn't been maintained for over two years. I don't think we recommend this to customers anymore so we should remove it from the list of recommended installs.
Removed the Next ACMS options from the `app:new` command.
We could choose to maintain the Next ACMS app, but that's would be a product decision. We should get someone from the Product org to approve this PR.
Run the `app:new` command. You should see two options. Prior to the PR, there were three options. I also added an assertion to `testNewDrupalCommand` that asserts this option is not there.
1. Follow the [contribution guide](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#building-and-testing) to set up your development environment …
=> Remove Next ACMS from list of new applications
